### ISSUE TITLE
SARSA on the Taxi Environment

### ISSUE THREAD

**Issue by khusheekapoor** [The-Data-Alchemists-Manipal/MindWave#10]
## 💥 Proposal

To implement the SARSA algorithm on the Taxi Environment.
Link to the Environment: https://www.gymlibrary.dev/environments/toy_text/taxi/

**Comment by hkcs1206** [comment]
Hey,
I am a GSSOC participant.
I want to work on this issue as I am experienced with Gym Library, where I worked on projects like Car Racing using DQN.
So, I would like to work on this issue and contribute.
