### ISSUE TITLE
[GSSOC'23] Object detection model using YOLOV5

### ISSUE THREAD

**Issue by mkswagger** [The-Data-Alchemists-Manipal/MindWave#101]
# Title: Proposal: Add YOLOv5 Object Detection Model

Description:
 Suggesting the inclusion of YOLOv5, a fast and accurate object detection model, to the repository. This model enables efficient detection and classification of objects in images and videos. To enhance the repository with advanced object detection capabilities.

**Comment by mkswagger** [comment]
Hi ,
I am a contributor in GSSOC'23 , I would love to contribute to this issue. Please assign this issue to me

**Comment by reshma045** [comment]
Hello, I'm GSSoC'23 Contributor. Please assign me this issue. I want to work on this and contribute to this.

**Comment by khusheekapoor** [comment]
@mkswagger - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by reshma045** [comment]
Thank you @khusheekapoor
