### ISSUE TITLE
Deep Facial Recognition Application for Authentication

### ISSUE THREAD

**Issue by Nandini-singh05** [The-Data-Alchemists-Manipal/MindWave#103]
## 💥 Proposal

I aim to undertake a project that aims to establish a comprehensive workflow for individuals seeking to leverage research papers for project development purposes. Specifically, I intend to develop a deep facial recognition application that can be used for authentication within other applications. To accomplish this, I will construct a model using the Deep Learning framework TensorFlow, which will emulate the methodology described in the research paper titled "Siamese Neural Networks for One-shot Image Recognition." Once the model is successfully trained, my objective is to seamlessly integrate it into an application to enable effective authentication.

Research Paper : [Siamese Neural Networks for One-shot Image Recognition](https://www.cs.cmu.edu/~rsalakhu/papers/oneshot1.pdf)

Dataset : [Labeled Faces in the Wild Home](http://vis-www.cs.umass.edu/lfw/)

**Comment by khusheekapoor** [comment]
@Nandini-singh05   - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
