### ISSUE TITLE
Duplicate Question Pairs

### ISSUE THREAD

**Issue by PRAVEENAPOTHI** [The-Data-Alchemists-Manipal/MindWave#107]
Proposal

Hi,@khusheekapoor  , i would like to contribute in this issue because For Example.... we have same words with different meanings but the prediction level for this is low so for this i choose random forest approach and also there comes a contextual Embeddings....like BERT 

The main abstract is to find whether the questions are duplicate or not
  
I want to work on this issue
I am a GSSOC'23 contributor

**Comment by khusheekapoor** [comment]
@PRAVEENAPOTHI we have a similar issue (#70). Hence, we won't be able to assign you this issue.
