### ISSUE TITLE
IEEE-CIS Fraud Detection

### ISSUE THREAD

**Issue by YB73** [The-Data-Alchemists-Manipal/MindWave#110]
## 💥 Proposal

Detecting fraud in customer transactions using Deep Learning.
Dataset link : https://www.kaggle.com/competitions/ieee-fraud-detection/data

**Comment by khusheekapoor** [comment]
@YB73 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
