### ISSUE TITLE
Heart Failure Prediction 

### ISSUE THREAD

**Issue by lcs2022026** [The-Data-Alchemists-Manipal/MindWave#112]
💥 Proposal
to create a model that can predict the heart failure of a person
I will use svm, randomforest ,and logistic model and would select the best of them
the dataset i am gonna use is :- https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction
@khusheekapoor 
I am GSSOC'23 contributor and would like to do this project 
so kindly assign this issue to me

**Comment by lcs2022026** [comment]
to create a model that can predict the heart failure of a person
I will use svm, randomforest ,and logistic model and would select the best of them
the dataset i am gonna use is :- https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction
@khusheekapoor
I am GSSOC'23 contributor and would like to do this project
so kindly assign this issue to me
@khusheekapoor

**Comment by khusheekapoor** [comment]
@lcs2022026  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
