### ISSUE TITLE
Brain Tumor Classification by ANN

### ISSUE THREAD

**Issue by lcs2022026** [The-Data-Alchemists-Manipal/MindWave#114]
💥 Proposal
to make a model that can classify the tumor into its respective category based on image
the dataset i am gonna use is:- https://www.kaggle.com/datasets/sartajbhuvaji/brain-tumor-classification-mri/code
@khusheekapoor 
I am GSSOC'23 contributor 
i would like to do this project 
so kindly assign this to me

**Comment by lcs2022026** [comment]
to make a model that can classify the tumor into its respective category based on image
the dataset i am gonna use is:- https://www.kaggle.com/datasets/sartajbhuvaji/brain-tumor-classification-mri/code
@khusheekapoor 
I am GSSOC'23 contributor 
i would like to do this project 
so kindly assign this to me

**Comment by khusheekapoor** [comment]
@lcs2022026  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
