### ISSUE TITLE
525 birds classification using the best model possible in DL

### ISSUE THREAD

**Issue by Kota-Karthik** [The-Data-Alchemists-Manipal/MindWave#115]
💥 Proposal
to classify the birds in respective categories based on its image
the dataset i would like to use is :- https://www.kaggle.com/datasets/gpiosenka/100-bird-species
@khusheekapoor 
I am GSSOC'23 contributor 
i would like to do this project 
so kindly assign me this issue

**Comment by lcs2022026** [comment]
to classify the birds in respective categories based on its image
the dataset i would like to use is :- https://www.kaggle.com/datasets/gpiosenka/100-bird-species
@khusheekapoor 
I am GSSOC'23 contributor 
i would like to do this project 
so kindly assign me this issue
@khusheekapoor

**Comment by khusheekapoor** [comment]
@lcs2022026 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
