### ISSUE TITLE
[GSSoC23] Brain Tumor Detection

### ISSUE THREAD

**Issue by dishamodi0910** [The-Data-Alchemists-Manipal/MindWave#118]
## 💥 Proposal
Making a *brain tumour* detection model using deep learning models. It will be deployed using Django as a web app where users can submit the MRI picture of their report and using deep learning models and MRI reports, they would be provided with the output. 

**Tech Stacks: Deep Learning and Image Processing**

**Comment by khusheekapoor** [comment]
@dishamodi0910 - we already have many such similar issues (#114 #36). Hence, we won't be able to assign you this issue.
