### ISSUE TITLE
Disease detection in Agriculture Domain - Potato Leaves

### ISSUE THREAD

**Issue by ArunMaramraj** [The-Data-Alchemists-Manipal/MindWave#120]
## 💥 Proposal
Disease detection in Potato leaves happen to affect farmers in drastic way as changes in early days of disease in the plant leaves is not visible clearly. I propose to build a DL model to classify the leaves as 'Late Blight' and 'Early blight' to help detect the disease in plant leaves early, so that farmer is insured of upcoming losses. 

I would follow this research paper for building the model: [Potato Disease Detection and classification using CNN](https://ijrpr.com/uploads/V3ISSUE5/IJRPR4071.pdf )

# Methodology : 

## Data Preprocessing : 
I will be using tf dataset and data augmentation. Data Augmentation is necessary incase enough set of diverse images aren't avilable on web.
## Model Used 
I will be using  CNN to build the model
## Additional Proposals:
Backend Server and ML Ops: tf serving, FastAPI
Model Optimization: Quantization, Tensorflow lite

I request you to assign me this issue as a part of GSSOC '23 programme. Thank You!

**Comment by khusheekapoor** [comment]
@ArunMaramraj - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
