### ISSUE TITLE
[docs]: Contributor section doesn't display contributors on readme

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [The-Data-Alchemists-Manipal/MindWave#123]
## 💥 Proposal
There's a bug in readme, where contributors section doesn't display contributors, actually.
I'd like to work.

**Comment by khusheekapoor** [comment]
@Soumya-Kushwaha - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!

**Comment by Soumya-Kushwaha** [comment]
Thank you @khusheekapoor
