### ISSUE TITLE
Credit Card Fraud Detection

### ISSUE THREAD

**Issue by sujanrupu** [The-Data-Alchemists-Manipal/MindWave#132]
## 💥 Proposal (GSSOC 23)

A machine learning algorithm to recognize fraudulent credit card transactions so that the customers of credit card companies are not charged for items that they did not purchase.

**Main challenges involved in credit card fraud detection are:**

1. Enormous Data is processed every day and the model build must be fast enough to respond to the scam in time.
2. Imbalanced Data i.e most of the transactions (99.8%) are not fraudulent which makes it really hard for detecting the fraudulent ones
3. Data availability as the data is mostly private.
4. Misclassified Data can be another major issue, as not every fraudulent transaction is caught and reported.
5. Adaptive techniques used against the model by the scammers.

**Comment by tanujbordikar** [comment]
I would like to work on this issue but can you elaborate more on what I need to do.

**Comment by theyashwanthsai** [comment]
@sujanrupu - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by theyashwanthsai** [comment]
@sujanrupu Please specify the ml model which you are going to train

**Comment by sujanrupu** [comment]
@theyashwanthsai  may I start working on the issue?

**Comment by theyashwanthsai** [comment]
@sujanrupu you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
