### ISSUE TITLE
GSSOC'23: Cloth Similarity Search

### ISSUE THREAD

**Issue by shashank1623** [The-Data-Alchemists-Manipal/MindWave#135]
## 💥 Proposal
Hey @khusheekapoor , i'm shashank bhardwaj GSSOC'23 contribute would like contribute a project for this repo.

The goal of this project is to create a machine learning model capable of receiving text describing a clothing item and returning a ranked list of links to similar items from different websites. 

please assign this issue to me!

**Comment by theyashwanthsai** [comment]
@shashank1623 Please tell us the ml model which you will be using and the link for the dataset on which you will be training your model.

**Comment by shashank1623** [comment]
I will be using TF-IDF( Term Frequency-Inverse Document Frequency that is commonly used in NLP) . and for datasets i will create my own datasets using web scraping method from various E-commerce application.

**Comment by shashank1623** [comment]
@theyashwanthsai  if you find this helpful for this repo pls assign it to me .

**Comment by theyashwanthsai** [comment]
@shashank1623 okay

**Comment by shashank1623** [comment]
assign this issue to me so that i can start working on it!

**Comment by khusheekapoor** [comment]
@shashank1623 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
