### ISSUE TITLE
Face Mask Detection 

### ISSUE THREAD

**Issue by Shreyg-27** [The-Data-Alchemists-Manipal/MindWave#140]
## 💥 Proposal

Using an appropriate machine learning model (VGG/YOLO/CNN) that would be able to detect whether a person is wearing a face mask.

**Comment by Shreyg-27** [comment]
Hi @khusheekapoor ! I am GSSoC'23 contributor and I raised this issue. Can you please assign this to me under the GSSoC'23 contribution. 
Thank you!

**Comment by Shreyg-27** [comment]
Hi @theyashwanthsai . Can you please assign this issue to me?

**Comment by theyashwanthsai** [comment]
@Shreyg-27 can you please provide the link for the dataset which you will be using.

**Comment by Shreyg-27** [comment]
> @Shreyg-27 can you please provide the link for the dataset which you will be using.

I will be working on this Kaggle dataset. 
https://www.kaggle.com/datasets/ashishjangra27/face-mask-12k-images-dataset

**Comment by khusheekapoor** [comment]
@Shreyg-27 - we have a similar issue on similar lines (#31). Hence, we won't be able to assign you this issue.
