### ISSUE TITLE
Traffic Sign Recognition - [GSSOC '23]

### ISSUE THREAD

**Issue by Soumya1219** [The-Data-Alchemists-Manipal/MindWave#141]
## 💥 Proposal

I am a Machine Learning enthusiast. I want to build Convolution Neural Network (CNN) model for Traffic Sign Recognition using Keras Library. 

Kindly assign this issue to me.

**Comment by theyashwanthsai** [comment]
@Soumya1219 please provide the dataset link which you will be using.

**Comment by Soumya1219** [comment]
https://www.kaggle.com/datasets/meowmeowmeowmeowmeow/gtsrb-german-traffic-sign

**Comment by theyashwanthsai** [comment]
cool
@Soumya1219 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
