### ISSUE TITLE
Customer Clustering 

### ISSUE THREAD

**Issue by Kota-Karthik** [The-Data-Alchemists-Manipal/MindWave#143]
💥 Proposal
I would like to make a model that could classify the customers into different groups.
the dataset i would like to use is:-https://www.kaggle.com/datasets/dev0914sharma/customer-clustering
@khusheekapoor  
I am a GSSOC'23 contributor ,i want to do this issue ,
so kindly please assign me the issue

**Comment by lcs2022026** [comment]
💥 Proposal
I would like to make a model that could classify the customers into different groups.
the dataset i would like to use is:-https://www.kaggle.com/datasets/dev0914sharma/customer-clustering
@khusheekapoor  
I am a GSSOC'23 contributor ,i want to do this issue ,
so kindly please assign me the issue
@khusheekapoor

**Comment by sarahcodebyte** [comment]
### Proposal
**@khusheekapoor ma'am, I am a GSSOC'23 contributor and would like to work on this project.**
**I would like to create a predictive model that would suggest to the company which group of customers(based on their shopping habits) should most likely be targeted for maximizing profit.**

**Link to the dataset that I would be using: https://www.kaggle.com/datasets/imakash3011/customer-personality-analysis**

**Kindly assign me this issue**

**Looking forward to contributing**

**Comment by theyashwanthsai** [comment]
@lcs2022026 please tell us which machine learning model you will be using. Thanks :)

**Comment by lcs2022026** [comment]
@theyashwanthsai 
i will use K-means clustering

**Comment by khusheekapoor** [comment]
@lcs2022026 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by impeccable16** [comment]
hi I want to work on this issue
