### ISSUE TITLE
Credit card clustering

### ISSUE THREAD

**Issue by Kota-Karthik** [The-Data-Alchemists-Manipal/MindWave#144]
💥 Proposal
@khusheekapoor 
to make a clustering model that can make groups of credit card customers 
the dataset i would like to use is:-https://www.kaggle.com/datasets/aryashah2k/credit-card-customer-data
i am interested in doing this issue so kindly assign me this issue

**Comment by lcs2022026** [comment]
💥 Proposal
@khusheekapoor 
to make a clustering model that can make groups of credit card customers 
the dataset i would like to use is:-https://www.kaggle.com/datasets/aryashah2k/credit-card-customer-data
i am interested in doing this issue so kindly assign me this issue
@khusheekapoor

**Comment by KomalT2003** [comment]
💥 Proposal:
@khusheekapoor 
With this , I aim to develop a clustering model which groups credit card holders based on their buying habits, credit limits, and many more financial factors. One great dataset I came from: 
https://www.kaggle.com/datasets/arjunbhasin2013/ccdata
Please assign this project to me!
I promise to work hard and complete it on time!

**Comment by theyashwanthsai** [comment]
@lcs2022026 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by theyashwanthsai** [comment]
@lcs2022026 Please tell us which clustering model you will be using.

**Comment by lcs2022026** [comment]
k means clustering

**Comment by theyashwanthsai** [comment]
okay

**Comment by lcs2022026** [comment]
@theyashwanthsai 
can i go ahead start doing the project?: )

**Comment by theyashwanthsai** [comment]
@lcs2022026 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
