### ISSUE TITLE
💥 LSTM-Next word prediction

### ISSUE THREAD

**Issue by NisargPipaliya** [The-Data-Alchemists-Manipal/MindWave#148]
## 💥 Next word prediction using LSTM

I am proposing to make a LSTM model to predict next word from the input given by the user.

@khusheekapoor 
Can you Please Assign me this issue?

**Comment by NisargPipaliya** [comment]
I will be just using text files.
And preprocessing it and regular stuff.

**Comment by NisargPipaliya** [comment]
@theyashwanthsai

**Comment by theyashwanthsai** [comment]
okay

**Comment by theyashwanthsai** [comment]
Will you be pushing the dataset as well? We will need to verify during pull request thats why.

**Comment by NisargPipaliya** [comment]
Don't worry,
I am pasting links to my dataset in notebooks

**Comment by NisargPipaliya** [comment]
And for this i will be using top novels of  this month.

**Comment by theyashwanthsai** [comment]
Okay cool.

**Comment by theyashwanthsai** [comment]
You will need to push the dataset as well.

**Comment by NisargPipaliya** [comment]
@theyashwanthsai

**Comment by khusheekapoor** [comment]
@NisargPipaliya - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by NisargPipaliya** [comment]
@theyashwanthsai PLS REVIEW AND MERGE

**Comment by impeccable16** [comment]
hey I want to work on this issue

**Comment by NisargPipaliya** [comment]
@khusheekapoor 
@theyashwanthsai 
Pls review and merge 😅
