### ISSUE TITLE
Improvise Machine Learning readme

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [The-Data-Alchemists-Manipal/MindWave#151]
## 💥 Proposal
Improvise the readme a little and sort the projects by algorithms so it becomes easier to navigate.

**Comment by srujana-16** [comment]
Hey! I would like to work on this issue, please assign it to me.

**Comment by khusheekapoor** [comment]
@Soumya-Kushwaha - we can do it halfway through the program? Say around June 30th?

**Comment by Soumya-Kushwaha** [comment]
@khusheekapoor alright, will stay tuned.

**Comment by khusheekapoor** [comment]
@Soumya-Kushwaha - please go ahead. Also, please clean up the readme by ensuring that all the notebooks/ folders have been linked. Thanks!

**Comment by khusheekapoor** [comment]
@Soumya-Kushwaha are you taking this up?

**Comment by Soumya-Kushwaha** [comment]
Yes yes, I am.
I'll work on it.
