### ISSUE TITLE
Drowsiness Detection Using YOLOV5

### ISSUE THREAD

**Issue by SAPNILPATEL** [The-Data-Alchemists-Manipal/MindWave#153]
## 💥 Proposal

Drowsiness detection plays a crucial role in ensuring the safety of individuals, especially in scenarios such as driving or operating heavy machinery. This proposal aims to develop a drowsiness detection system using the YOLOv5 object detection algorithm.

**Comment by khusheekapoor** [comment]
@SAPNILPATEL  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by khusheekapoor** [comment]
@tanujbordikar  - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue on the similar lines.

**Comment by SAPNILPATEL** [comment]
> Please provide the dataset link.

I will test this model on my own dataset.
