### ISSUE TITLE
Face Emotion Detection 

### ISSUE THREAD

**Issue by aman-kumar29** [The-Data-Alchemists-Manipal/MindWave#154]
## 💥 Proposal
I propose an Emotion Detection System based on computer vision using deep learning techniques. The system will analyze real-time facial expressions and accurately classify emotions. By training a model on a diverse dataset, optimizing it with the Adam optimizer, and implementing live emotion detection from a camera feed, this system aims to provide accurate and efficient emotion recognition. The project will be evaluated for its performance and effectiveness, and the final deliverable will be an IPython Notebook showcasing the code, model training, and evaluation results.

I want to do it under GSSoC'23 so can you please assign this project to me?

(A clear and concise description of what the proposal is.)

**Comment by 15IITian** [comment]
I also want to work on it, please assign it to me.

**Comment by theyashwanthsai** [comment]
@aman-kumar29 can you please tell us which model you will be using? and also provide the link for the dataset.

**Comment by aman-kumar29** [comment]
Hi, I am thinking of using some pretrained model like resnet50, VGG-16 etc and building the  model architecture from there. I will be using FER-2013 Dataset for this.

**Comment by theyashwanthsai** [comment]
@aman-kumar29  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by aman-kumar29** [comment]
@theyashwanthsai can you please check this and tell me if I need to make any changes?
