### ISSUE TITLE
💥 EDA on sales data

### ISSUE THREAD

**Issue by NisargPipaliya** [The-Data-Alchemists-Manipal/MindWave#156]
## 💥 Proposal to make a Data Analysis project

I have an Idea to make a project, performing EDA on Sales Dataset and finding out which users tend to spend more in festive seasons.

@khusheekapoor 
Can you Assign me this issue?

**Comment by asthabarwal** [comment]
Hey @khusheekapoor I would like to work on this project to bring out useful conclusions from the sales dataset by EDA. Can this project be assigned to me?

**Comment by NisargPipaliya** [comment]
@khusheekapoor  -> Please Assign the issue

@asthabarwal 
the issues are assigned on First come First Serve basis :)

**Comment by theyashwanthsai** [comment]
@NisargPipaliya Please provide the link for the dataset which you will be using

**Comment by NisargPipaliya** [comment]
At present i don't have a kaggle link, i have this at present.

I can search for it...if needed

**Comment by theyashwanthsai** [comment]
its fine

**Comment by theyashwanthsai** [comment]
you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
 Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by theyashwanthsai** [comment]
@NisargPipaliya Please tell us which ml model you will be using

**Comment by NisargPipaliya** [comment]
It is data analysis so, i won't be making any models.

Can you please checkout the reference.ipynb in data analytics folder.

**Comment by theyashwanthsai** [comment]
Oh sorry sorry i got confused with another issue

**Comment by theyashwanthsai** [comment]
@NisargPipaliya  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by NisargPipaliya** [comment]
@theyashwanthsai 
Can you please review and merge it?
