### ISSUE TITLE
AI Image Search System

### ISSUE THREAD

**Issue by ayush-09** [The-Data-Alchemists-Manipal/MindWave#157]
## Description
The AI Image Search project is focused on developing an advanced system that utilizes artificial intelligence techniques to enable efficient and accurate searching of images based on their visual content. The project involves training a deep learning model on a diverse dataset of labeled images, extracting meaningful features from images, creating an index for storage and retrieval, and implementing a user-friendly interface for search queries and result presentation. The ultimate goal is to revolutionize image search in various domains, enhancing image retrieval, content organization, and user experiences.

### Goals
Develop an AI-powered image recognition model capable of accurately understanding and analyzing the visual content of images.
Design a user-friendly interface that allows users to easily initiate image searches, provide reference images or keywords, and obtain relevant and visually similar results.
Improve user experiences by providing a powerful and intuitive image search tool that saves time and effort in finding the desired images.

### Methodology
![Methodology](https://github.com/The-Data-Alchemists-Manipal/MindWave/assets/51924622/71db7727-abcd-4928-8603-93ede5d29879)

**Comment by theyashwanthsai** [comment]
@ayush-09 Please tell us which dataset will you be using. also provide the link to the dataset.

**Comment by ayush-09** [comment]
@theyashwanthsai I will be using CIFAR-10 from kaggle as well as from the CIFAR-10 Dataset Mirror for easy handling
https://pjreddie.com/projects/cifar-10-dataset-mirror/

**Comment by theyashwanthsai** [comment]
Okay, you will be using cnn right? i need to know the algorithm which you will be using to add the proper label

**Comment by theyashwanthsai** [comment]
@ayush-09 you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by ayush-09** [comment]
@theyashwanthsai @khusheekapoor Please review my PR and kindly merge it if everything is alright and give the GSSOC tag.
