### ISSUE TITLE
Profanity checker using NLP.

### ISSUE THREAD

**Issue by okaditya84** [The-Data-Alchemists-Manipal/MindWave#162]
## 💥 Proposal

Implementing a profanity (NSFW words) checker that can convert audio file or one can speak through mic as well, that can understand the context of the speech and detects the target words. It will be useful if we scale this up and then it can be implemented in platforms like youtube, discord, slack, instagram, twitter etc to segregate content in different sections.

**Comment by theyashwanthsai** [comment]
Hello, can you please give more details about your proposal? like the model you are going to use and what dataset you are going to it train on.

**Comment by okaditya84** [comment]
> Hello, please provide more explanation about your proposal. The model which you are going to use and the dataset which u will training it on. Thank you

I will be using concepts of NLP and training dataset source : [[https://www.kaggle.com/datasets/mrmorj/hate-speech-and-offensive-language-dataset?select=labeled_data.csv](url)

It will be accurate enough to detect most used words.

**Comment by theyashwanthsai** [comment]
Ok cool

**Comment by theyashwanthsai** [comment]
The link doesn't work :0

**Comment by okaditya84** [comment]
> The link doesn't work :0

Here is the full working link : [https://www.kaggle.com/datasets/mrmorj/hate-speech-and-offensive-language-dataset?select=labeled_data.csv](url)

**Comment by theyashwanthsai** [comment]
@okaditya84 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by theyashwanthsai** [comment]
@okaditya84 which ml model are you using? tell me so I can add appropriate tag to this issue

**Comment by okaditya84** [comment]
> @okaditya84 which ml model are you using? tell me so I can add appropriate tag to this issue

I'm using APIs, RNN, LSTM.
Kindly assign the tag gssoc23 too.
Thanks.

**Comment by theyashwanthsai** [comment]
okay
