### ISSUE TITLE
Fake News Detection - [GSSOC'23]

### ISSUE THREAD

**Issue by Durga-Sowjanya-Sanku** [The-Data-Alchemists-Manipal/MindWave#163]
#### We can use the NEWS dataset from KAGGLE and detect whether or not that is fake news.
1. We can use the suitable machine learning algorithms to deal with this dataset.
2. The best model  RandomForestClassifier, Logistic Regression and SVM
3. It will also help those to understand how to deal with text data and process the data.
4. Can come across different encoding techniques (Categorical Encoding, One HOT Encoding)

### I would love to help those who want to learn Machine Learning with a diverse data and find the relevant models.

[True.csv.zip](https://github.com/The-Data-Alchemists-Manipal/MindWave/files/11546510/True.csv.zip)
[Fake.csv.zip](https://github.com/The-Data-Alchemists-Manipal/MindWave/files/11546520/Fake.csv.zip)

**Comment by theyashwanthsai** [comment]
Hi. If there is a link to the kaggle dataset, please provide it :)

**Comment by Durga-Sowjanya-Sanku** [comment]
> Hi. If there is a link to the kaggle dataset, please provide it :)

This is the link where I got to find the good dataset for Fake News Detection: 

https://www.kaggle.com/code/therealsampat/fake-news-detection/input

**Comment by Durga-Sowjanya-Sanku** [comment]
> Hi. If there is a link to the kaggle dataset, please provide it :)

I have uploaded the link.
Can you please go through it..
