### ISSUE TITLE
WCE Curated Colon Disease classification Deep Learning using CNN

### ISSUE THREAD

**Issue by lcs2022026** [The-Data-Alchemists-Manipal/MindWave#168]
## 💥 Proposal
i want to make a model that can classify colon disease based on its image
the dataset i am gonna use is:-https://www.kaggle.com/datasets/francismon/curated-colon-dataset-for-deep-learning
@khusheekapoor 
I am GSSOC'23 contributor 
I want to do this project so kindly assign me this issue

**Comment by lcs2022026** [comment]
i want to make a model that can classify colon disease based on its image
the dataset i am gonna use is:-https://www.kaggle.com/datasets/francismon/curated-colon-dataset-for-deep-learning
@khusheekapoor 
I am GSSOC'23 contributor 
I want to do this project so kindly assign me this issue

**Comment by theyashwanthsai** [comment]
Which ml model will you be using? kindly specify the model you will be using, the dataset u will be training it on and the link to the dataset.

**Comment by theyashwanthsai** [comment]
Will you be using convolution neural net?
kindly specify it in your comment :)

**Comment by lcs2022026** [comment]
Yes
@theyashwanthsai

**Comment by khusheekapoor** [comment]
@lcs2022026  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
