### ISSUE TITLE
Eye disease classification (flaky corneal ulcers) using ANN

### ISSUE THREAD

**Issue by lcs2022026** [The-Data-Alchemists-Manipal/MindWave#169]
## 💥 Proposal
to make a ANN model that classifies flaky corneal ulcers 
the dataset i am gonna use is:-https://www.kaggle.com/datasets/bongsang/eye-disease-deep-learning-dataset
@khusheekapoor 
I am GSSOC'23 contributor 
i am interested in doing this project 
so kindly assign me this issue

**Comment by lcs2022026** [comment]
@khusheekapoor 
to make a ANN model that classifies flaky corneal ulcers 
the dataset i am gonna use is:-https://www.kaggle.com/datasets/bongsang/eye-disease-deep-learning-dataset
@khusheekapoor 
I am GSSOC'23 contributor 
i am interested in doing this project 
so kindly assign me this issue

**Comment by theyashwanthsai** [comment]
@lcs2022026 you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_datasetname.ipynb` and link it in the readme of the labeled directory as `algorithm - datasetname`. Thank you :)
