### ISSUE TITLE
News Category Detection Model

### ISSUE THREAD

**Issue by ayon037** [The-Data-Alchemists-Manipal/MindWave#176]
## 💥 Proposal

We can use the News Category Dataset dataset from KAGGLE to detect which type of news it was.

1. We can use suitable machine learning algorithms to deal with this dataset.
2. The best model RandomForestClassifier, Logistic Regression, Naive Bayes
3. It will help to categorize the news to recommend news to people based on their interests.
4. Can do some data cleaning and processing techniques to get the best outcome from the model.

I would love to help those who want to learn Machine Learning with diverse data and find the relevant models.

The following dataset can be used from Kaggle: 
https://www.kaggle.com/datasets/rmisra/news-category-dataset/code

I would love to contribute to the issue.
Could you assign me this under GSSOC'23? It would be beneficial.
Pre-requisite: I'm a GSSOC'23 open-source contributor.

**Comment by theyashwanthsai** [comment]
@ayon037  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
