### ISSUE TITLE
Add CONTRIBUTING.md file 

### ISSUE THREAD

**Issue by ImranNawar** [The-Data-Alchemists-Manipal/MindWave#177]
Hi there!
I recommend adding a **CONTRIBUTING.md** file to your repository. This file would serve as a guide for potential contributors, outlining the project's contribution guidelines, coding conventions, and steps to follow when raising issues or submitting pull requests. It will help streamline the contribution process and provide clarity to newcomers.

I would like to work on this issue. Please assign it to me under **GSSoC'23.**

Thank you!

**Comment by khusheekapoor** [comment]
@ImranNawar - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!
