### ISSUE TITLE
Wine Quality Prediction

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [The-Data-Alchemists-Manipal/MindWave#178]
## 💥 Proposal

Wine Quality Prediction using machine learning algorithms

**Comment by asthabarwal** [comment]
Hey @khusheekapoor  i would love to work on this issue , please assign this to me.

**Comment by theyashwanthsai** [comment]
@asthabarwal since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue and use the same algorithm on a different dataset.

**Comment by theyashwanthsai** [comment]
@Soumya-Kushwaha Please give a link for the dataset.

**Comment by khusheekapoor** [comment]
@Soumya-Kushwaha - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
