### ISSUE TITLE
"CERN Electron Collision Data" using AdaBoost 

### ISSUE THREAD

**Issue by Shubhra-31** [The-Data-Alchemists-Manipal/MindWave#180]
To create a model using AdaBoost to predict the invariant mass of the colliding electrons .
The link for the dataset is : 
https://www.kaggle.com/datasets/fedesoriano/cern-electron-collision-data
I am a GSSOC'23 contributor and would love to contribute.
So kindly assign this issue to me.

**Comment by theyashwanthsai** [comment]
@Shubhra-31 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by Shubhra-31** [comment]
Could you also add the difficulty level and gssoc tag ?

**Comment by Shubhra-31** [comment]
Also, I plan to use optuna for hyper parameter tuning.

**Comment by theyashwanthsai** [comment]
@Shubhra-31 yes we will be doing it. We need some time :)
