### ISSUE TITLE
Drowsiness Detection to improve Study Efficiency 

### ISSUE THREAD

**Issue by KomalT2003** [The-Data-Alchemists-Manipal/MindWave#183]
## 💥 Proposal

For students studying online, a drowsiness Detection system can be made which alerts the user when he or she starts feeling drowsy and unfocused. This alarm will bring the student to focus back.
The dataset that can be used is :
https://www.kaggle.com/datasets/rakibuleceruet/drowsiness-prediction-dataset

@khusheekapoor 
I am a GSSOC '23 contributor. I am really keen to contribute on this project . Kindly assign it to me!

**Comment by VishalVinayRam** [comment]
Sir i want to work on this can u assign this me

**Comment by theyashwanthsai** [comment]
@KomalT2003 This is a duplicate issue. #153 Check this issue. Since we are following the first-come-first-serve policy, we cannot assign you this issue. However, you can create another issue and use the same algorithm on a different dataset.
