### ISSUE TITLE
Add cross validation techniques 

### ISSUE THREAD

**Issue by KaviRana** [The-Data-Alchemists-Manipal/MindWave#187]
## 💥 Proposal

Cross validation is a technique used to evaluate the performance of a machine learning model. 

I suggest adding the following cross validation techniques to the MindWave repository:

Hold Out Validation
K-fold Cross-Validation.
Stratified K-fold Cross-Validation
Leave One Out Cross-Validation.
Repeated Random Test-Train Splits

I will add all of these with clear explanations, so that beginners in data science can understand.

**Comment by Vethan123** [comment]
Hi @KaviRana  I think I can work on this  and provide you results with a detailed explanation. Please assign this to me

**Comment by KaviRana** [comment]
@Vethan123 I am a contributor not the maintainer of this repo. I cannot assign you this. I raised this issue so I can work on this.

**Comment by KaviRana** [comment]
@khusheekapoor please assign this issue to me

**Comment by Vethan123** [comment]
@KaviRana  i liked this issue. I am also willing to work on this.please allow me to work with you.

**Comment by theyashwanthsai** [comment]
@velthan since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue and use the same algorithm on a different dataset.

**Comment by theyashwanthsai** [comment]
@KaviRana this looks interesting, you can open separate issues for each technique, and different datasets for each technique. provide the link for dataset, and model you will be using.

**Comment by KaviRana** [comment]
ok. I will use this issue as the main issue and will link all the sub issues here.

**Comment by theyashwanthsai** [comment]
@KaviRana okay I will look into it. please give us some time.
