### ISSUE TITLE
Blood cells classification using ANN

### ISSUE THREAD

**Issue by Kota-Karthik** [The-Data-Alchemists-Manipal/MindWave#189]
## 💥 Proposal
I want to create a model that classifies the image of blood cell into its respective category
i am gonna make this model by using Artificial Neural Network(ANN)
the dataset i am gonna use is:-https://www.kaggle.com/datasets/paultimothymooney/blood-cells
@theyashwanthsai  @khusheekapoor 
I am interested in doing this project 
so kindly assign me this

**Comment by lcs2022026** [comment]
I want to create a model that classifies the image of blood cell into its respective category
i am gonna make this model by using Artificial Neural Network(ANN)
the dataset i am gonna use is:-https://www.kaggle.com/datasets/paultimothymooney/blood-cells
@theyashwanthsai  @khusheekapoor 
I am interested in doing this project 
so kindly assign me this
@theyashwanthsai  @khusheekapoor

**Comment by theyashwanthsai** [comment]
@lcs2022026 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
