### ISSUE TITLE
Add a new project under the Data Analytics title.

### ISSUE THREAD

**Issue by tanujbordikar** [The-Data-Alchemists-Manipal/MindWave#195]
## 💥 Proposal

Hello there, I wanted to add a new project under the Data Analytic Title. So I request you both (@theyashwanthsai and @khusheekapoor )to assign me that work. 
For this I will work on the Supermart Grocery Sales dataset on kaggle to create some analytics and insights on that.
I will make analysis based on the category, sub-category, discount, and sales & report by region/city.
dataset link: https://www.kaggle.com/datasets/mohamedharris/supermart-grocery-sales-retail-analytics-dataset

**Comment by theyashwanthsai** [comment]
@tanujbordikar - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by VikasKumar2001** [comment]
Title: Adding Data Analytics and Machine Learning Project on Heart Failure Dataset

Description:
Hello [@theyashwanthsai] and [@khusheekapoor],

I would like to propose a new project under the Data Analytics category, focusing on analyzing and machine learning model on the Heart Failure dataset available on Kaggle. The dataset can be found at the following link: https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction
