### ISSUE TITLE
Indian Racial Crime Analysis

### ISSUE THREAD

**Issue by ritikalath30** [The-Data-Alchemists-Manipal/MindWave#196]
## 💥 Proposal

A complete analysis of caste-based crime in India helps in understanding the state that is most affected by it so further actions can be taken.
I wish to do the analysis and request @theyashwanthsai and @khusheekapoor to assign me this issue for the Data Analysis section.
I will be using an already existing dataset to perform the analysis.
Dataset to be used [https://www.kaggle.com/datasets/khalidative/crimeanalysis?select=crime_by_state.csv]()

**Comment by theyashwanthsai** [comment]
@ritikalath30 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by ritikalath30** [comment]
Thankyou
