### ISSUE TITLE
Chess piece Detection using ANN

### ISSUE THREAD

**Issue by lcs2022026** [The-Data-Alchemists-Manipal/MindWave#197]
## 💥 Proposal
I want to create a model that detects a chess piece and classifies into its respective category 
I will make this model using Artificial Neural Network (ANN) in Deep learning 
the dataset i am gonna use is:-https://www.kaggle.com/datasets/anshulmehtakaggl/chess-pieces-detection-images-dataset
@theyashwanthsai  @khusheekapoor 
I am interested in doing this project
 so kindly assign me this issue  : )

**Comment by lcs2022026** [comment]
I want to create a model that detects a chess piece and classifies into its respective category
I will make this model using Artificial Neural Network (ANN) in Deep learning
the dataset i am gonna use is:-https://www.kaggle.com/datasets/anshulmehtakaggl/chess-pieces-detection-images-dataset
@theyashwanthsai @khusheekapoor
I am interested in doing this project
so kindly assign me this issue : )
@theyashwanthsai @khusheekapoor

**Comment by BabarRasheed** [comment]
Hi!
I want to work on this issue as a part of GSSoC'23.  Could you please assign me and I am giving you my best and 100%.

**Comment by khusheekapoor** [comment]
@lcs2022026 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by khusheekapoor** [comment]
@BabarRasheed - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue on the similar lines.
