### ISSUE TITLE
Implementation of Generative Adversarial Network (GAN) for MNIST Handwritten Digits From Scratch in Keras

### ISSUE THREAD

**Issue by SAPNILPATEL** [The-Data-Alchemists-Manipal/MindWave#20]
## 💥 Proposal

I want to implement a Generative Adversarial Network (GAN) from scratch using the Keras framework to generate realistic MNIST handwritten digits. This GAN will consist of a generator and a discriminator, where the generator will learn to generate realistic digits, and the discriminator will learn to distinguish between real and generated digits.

I would like to request that you please assign it to me under the tag/label GSSoC'23.

**Comment by khusheekapoor** [comment]
@SAPNILPATEL  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by khusheekapoor** [comment]
@UditSharma9999 - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue on the similar lines.
