### ISSUE TITLE
Arabic Hand written letters classification by using ANN

### ISSUE THREAD

**Issue by lcs2022026** [The-Data-Alchemists-Manipal/MindWave#200]
## 💥 Proposal
I want to make a model that can predict the arabic letter written in the image 
I want to make this model using ANN(Artificial neural network)
the dataset i am gonna use is :-https://www.kaggle.com/datasets/mloey1/ahcd1
@theyashwanthsai @khusheekapoor 
I am interested in doing this project 
so kindly assign me this issue : )

**Comment by khusheekapoor** [comment]
@lcs2022026 -  you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
