### ISSUE TITLE
Customer churn prediction using ANN 

### ISSUE THREAD

**Issue by NisargPipaliya** [The-Data-Alchemists-Manipal/MindWave#21]
# 💥 Proposal

Here we are going to measure how and why are customers leaving the business, i.e.  Customer churn prediction using artificial neural networks.

**Comment by NisargPipaliya** [comment]
@khusheekapoor  I would like to work on this project.
Can you please assign it to me?

**Comment by khusheekapoor** [comment]
@NisargPipaliya  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by NisargPipaliya** [comment]
OK

**Comment by NisargPipaliya** [comment]
@khusheekapoor 
In the contribution guidelines, it is given that we should create separate branch, but if I just fork it, then wouldn't it be ok?
