### ISSUE TITLE
Breast Cancer Prediction

### ISSUE THREAD

**Issue by adityabachu** [The-Data-Alchemists-Manipal/MindWave#211]
## 💥 Proposal

I am a GSSoC Contributor, I want to add new project under Machine Learning Section that is Breast Cancer Prediction

I will be importing the dataset from the scikit-learn library and will be using logistic regression algorithm for this project, Please assign this issue to me.

**Comment by BabarRasheed** [comment]
Hi,
I'm Babar Rasheed (Contributor GSSOC'23).
I will be using the sci-kit-learn datasets for this project. I can give you my best as a data scientist.

**Comment by khusheekapoor** [comment]
@adityabachu  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
