### ISSUE TITLE
Image Classification fastai [GSSoC'23]

### ISSUE THREAD

**Issue by Rushi7667** [The-Data-Alchemists-Manipal/MindWave#212]
## 💥 Proposal

Hi, I am Rushi. As a GSSoC'23 contributor I want to apply my knowledge in Image Classification project using fastai library.
fastai is all in one deep learning library which is used for Computer Vision Tasks. As a Machine Learning enthusiast I want to work on this.
So please assign this to me.

#### dataset link - https://www.kaggle.com/datasets/puneet6060/intel-image-classification

**Comment by khusheekapoor** [comment]
@Rushi7667  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
