### ISSUE TITLE
Exploring Decision Trees for Classification and Regression Problems

### ISSUE THREAD

**Issue by kunal1383** [The-Data-Alchemists-Manipal/MindWave#219]
## 💥 Proposal

I want to propose an informative and comprehensive guide that explains the concepts and implementation of decision trees for classification and regression tasks using Scikit-learn. We will be using two datasets The California Housing dataset  which is  commonly used for regression tasks to predict the median house values in different locations in California and The Bank Marketing Dataset is typically used for classification tasks.

**Comment by Akhil-77** [comment]
I can do that can you give me the link for the datasets ?

**Comment by khusheekapoor** [comment]
@kunal1383 - please link the dataset that you will be using.

**Comment by kunal1383** [comment]
@khusheekapoor - sorry for the incomplete proposal, as for the dataset we are using two datasets  The California Housing dataset and the Bank Marketing Dataset. I have updated the proposal

**Comment by Sar-thak-3** [comment]
I already worked with classification and regression models and with these datasets, kindly assign me this issue under GSSoC 23
