### ISSUE TITLE
adding tech stack badges in readme 

### ISSUE THREAD

**Issue by mridulsaggi** [The-Data-Alchemists-Manipal/MindWave#220]
i would like to add tech stack badges and shields in readme . it makes the readme look more pretty and give better information about the technologies used.
please assign me this issue as gssoc contribution
example:
![image](https://github.com/The-Data-Alchemists-Manipal/MindWave/assets/91930535/dc6141bc-08da-4727-8f77-e980b490cf1a)

**Comment by khusheekapoor** [comment]
@mridulsaggi - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!
