### ISSUE TITLE
Adding New Category : Image Processing

### ISSUE THREAD

**Issue by dishamodi0910** [The-Data-Alchemists-Manipal/MindWave#221]
## 💥 Proposal

Adding new codes based on Hough Transform, Morphological Transformations, Detection of Objects, Contours, etc.

**Comment by khusheekapoor** [comment]
@dishamodi0910 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!

**Comment by dishamodi0910** [comment]
Thank you so much!!
