### ISSUE TITLE
ECG Heartbeat Categorization using CNN 

### ISSUE THREAD

**Issue by Kota-Karthik** [The-Data-Alchemists-Manipal/MindWave#224]
## 💥 Proposal
I want to create a model that can classify ECG 
I will make this model using Convolutional neural network in deep learning 
the dataset i am gonna use is :- https://www.kaggle.com/datasets/shayanfazeli/heartbeat?datasetId=29414
@theyashwanthsai  @khusheekapoor 
I am GSSOC'23 contributor 
I want to do this project
So, kindly assign me this.

**Comment by lcs2022026** [comment]
I want to create a model that can classify ECG 
I will make this model using Artificial neural network in deep learning 
the dataset i am gonna use is :- https://www.kaggle.com/datasets/shayanfazeli/heartbeat?datasetId=29414
@theyashwanthsai  @khusheekapoor 
I am GSSOC'23 contributor 
I want to do this project
So, kindly assign me this.
@theyashwanthsai  @khusheekapoor

**Comment by khusheekapoor** [comment]
@lcs2022026  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
