### ISSUE TITLE
Implementing UCB Algorithm for solving Multi Armed Bandit

### ISSUE THREAD

**Issue by tarun25c** [The-Data-Alchemists-Manipal/MindWave#229]
## 💥 Proposal

I will try to implement `Upper Confidence Bound Algorithm` to solve a Multi Armed Bandit problem in the `Reinforcement Learning` file.

**Comment by khusheekapoor** [comment]
@tarun25c  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
