### ISSUE TITLE
[GSSOC '23]Performing Data Analytics on Uber Dataset.

### ISSUE THREAD

**Issue by karthikbhandary2** [The-Data-Alchemists-Manipal/MindWave#235]
I would like to perform data analysis on the Uber dataset and try to implement a machine-learning model. I would also like to point out that I would be using different types of charts to perform data analysis.

**Comment by khusheekapoor** [comment]
@karthikbhandary2 - we already have another issue on the same (#72). Hence, we won't be able to allot you this issue.

**Comment by karthikbhandary2** [comment]
Can I at least make a machine learning model which runs on this dataset?
