### ISSUE TITLE
Add Logistic Regression model for the Portuguese banking dataset

### ISSUE THREAD

**Issue by lakshmishreea122003** [The-Data-Alchemists-Manipal/MindWave#237]
## 💥 Proposal
Dataset = [Portuguese banking dataset](https://archive.ics.uci.edu/ml/datasets/bank+marketing)
Model = Logistic Regression
Description = I would like to contribute a logistic regression model for the Portuguese banking dataset to the existing repository. The dataset contains information related to direct marketing campaigns of a Portuguese banking institution, and the goal is to predict if the client will subscribe a term deposit.

**Comment by lakshmishreea122003** [comment]
I am a contributor under GSSoC23 and wish to work on this issue. Kindly assign it to me.

**Comment by khusheekapoor** [comment]
@lakshmishreea122003 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
