### ISSUE TITLE
Heart Disease Prediction using ML

### ISSUE THREAD

**Issue by VB-deeksha** [The-Data-Alchemists-Manipal/MindWave#240]
## Proposal 
I want to contribute on this heart disease project, the dataset is available on Kaggle.com website here is the link https://www.kaggle.com/datasets/johnsmith88/heart-disease-dataset.

![image](https://github.com/The-Data-Alchemists-Manipal/MindWave/assets/96589133/5928a1c8-60e1-4269-8f26-acd9ee7535f9)

_The image shows brief introduction of Machine Learning and how the process will takes places._

In this project we will predict whether the person is having Heart Disease or not using Machine Learning Model.

**I want to work on this issue, @khusheekapoor please assign this to me.** 
Thank you.

**Comment by khusheekapoor** [comment]
@VB-deeksha - we have many similar issues. Hence, we won't be able to assign you this.
