### ISSUE TITLE
Global Energy Statistics

### ISSUE THREAD

**Issue by Akhil-77** [The-Data-Alchemists-Manipal/MindWave#247]
## Project Description
I have completed a detailed Exploratory Data Analysis (EDA) and Time Series Analysis of world energy data. The project aims to provide insights into global energy consumption, production, and trends over time. It includes comprehensive visualizations, statistical analysis, and modeling techniques specific to time series data. The Dataset can be downloaded from [here](https://www.kaggle.com/datasets/akhiljethwa/world-energy-statistics) and it was also made by me.

## Project Features
- Exploratory Data Analysis (EDA) of world energy data
- Time series analysis techniques, including decomposition, forecasting, and trend analysis
- Visualization of energy consumption and production patterns
- Statistical analysis of energy data
- Python implementation using popular data analysis libraries such as Pandas, LSTM, Plotly, stats models.

## Additional Information
I have already completed the project and would like to contribute it to the repository. The code is well-documented and adheres to best practices in data analysis. I believe that this project can be a valuable addition to the repository and can benefit researchers and data enthusiasts interested in the field of global energy analysis. If you want you can check out the project [here](https://github.com/Akhil-77/Global_Energy_Statistics).

**Comment by Akhil-77** [comment]
Please assign this to me :)

**Comment by theyashwanthsai** [comment]
this seems cool best of luck :)

@Akhil-77 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
