### ISSUE TITLE
[MODEL] Effective Targeting of Advertisments

### ISSUE THREAD

**Issue by himanshu-03** [The-Data-Alchemists-Manipal/MindWave#248]
## 💥 Proposal

Hello!
I am Himanshu Agarwal, a proud contribtuor at GSSoC '23. I would like to the contribute to this repo.

**Effective Targetting of Advertisments**: A Machine Learning project which will help us to predict the number of clicks on a particular ad on the websites.

Dataset Link: [Effective Targetting of Advertisments](https://www.kaggle.com/datasets/hiimanshuagarwal/advertising-ef)

Things I will be doing as of now:

- [x] Implementing the model under the `Machine Learning` category

**Comment by theyashwanthsai** [comment]
@himanshu-03 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by himanshu-03** [comment]
Sure!
Will be working in the given deadline ✌️

**Comment by himanshu-03** [comment]
> @himanshu-03 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

Sure!
Will be working in the given deadline ✌️

**Comment by himanshu-03** [comment]
> @himanshu-03 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

Hello @theyashwanthsai! 

💯 I have successfully implemented the **Effective Targeting of Advertisments Model**.

🔗 You can check here: [Effective Targeting of Advertisments](https://github.com/himanshu-03/MindWave/tree/main/Machine%20Learning/Effective%20Targeting%20of%20Advertisments)

✌🏻 Do review the PR here: #308
