### ISSUE TITLE
Loan Repayment System

### ISSUE THREAD

**Issue by Shashank1130** [The-Data-Alchemists-Manipal/MindWave#25]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
With the help of this project we can predict weather or nor a borrower will pay back their loan.
I will use ANN and Deep Learning for this project and EDA for better understanding of dataset.

**Comment by khusheekapoor** [comment]
@Shashank1130   - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
