### ISSUE TITLE
💥 Making Model Using DBSCAN 

### ISSUE THREAD

**Issue by NisargPipaliya** [The-Data-Alchemists-Manipal/MindWave#251]
## 💥 Proposal

To Make a Machine Learning Classification Model Using DBSCAN,  which is help full  on noisy data and create a perfect cluster.

 [Dataset](https://www.kaggle.com/datasets/vjchoudhary7/customer-segmentation-tutorial-in-python) - Mall Customer Segmentation

**Comment by NisargPipaliya** [comment]
@khusheekapoor 
Can you please assign this issue to me?

**Comment by theyashwanthsai** [comment]
@NisargPipaliya - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
