### ISSUE TITLE
Flappy Bird Game Agent 

### ISSUE THREAD

**Issue by ayush-09** [The-Data-Alchemists-Manipal/MindWave#252]
## 💥 Proposal

This is the AI agaent which addapt the environment of the Flappy Bird Game using **Reinforcement Learning** with Open AI Gym environment.

### Performance of  Agent
https://user-images.githubusercontent.com/51924622/121337387-1dca1080-c93a-11eb-9b9f-61bf00bc327f.mp4

**Comment by ayush-09** [comment]
@theyashwanthsai @khusheekapoor Please assign me this task.

**Comment by theyashwanthsai** [comment]
@ayush-09 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by ayush-09** [comment]
@theyashwanthsai @khusheekapoor Please review my PR and provide the gssoc tag
