### ISSUE TITLE
How to use Django for deploying models? [Deployed Projects]

### ISSUE THREAD

**Issue by dishamodi0910** [The-Data-Alchemists-Manipal/MindWave#253]
## 💥 Proposal
It will consider a text file describing how machine learning models can be deployed in a web app using Django.

Major Mentions : 
1. Basic description of Django.
2. About pickle files and how to generate pickle files.
3. How to store the best model?
4. How to take inputs from user and process the values.

**Comment by dishamodi0910** [comment]
@khusheekapoor I would like to work on this issue. Please assign it to me.

**Comment by theyashwanthsai** [comment]
@dishamodi0910 Is this a non code contribution?

**Comment by theyashwanthsai** [comment]
@dishamodi0910  you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm.py` and link it in the readme of the labeled directory as `algorithm - dataset`.
