### ISSUE TITLE
Brain-tumor-classification   by the best model possible

### ISSUE THREAD

**Issue by Viswaraje** [The-Data-Alchemists-Manipal/MindWave#255]
## 💥 Proposal
@khusheekapoor
the dataset i will use is here-https://www.kaggle.com/datasets/sartajbhuvaji/brain-tumor-classification-mri
please assign this project to me
i will use many different models and then i would select the model which would give me the best results
I am GSSOC'23 contributor and  would like to do this project

**Comment by Viswaraje** [comment]
Hello @khusheekapoor
the dataset i will use is here-https://www.kaggle.com/datasets/sartajbhuvaji/brain-tumor-classification-mri
please assign this project to me
i will use many different models and then i would select the model which would give me the best results
I am GSSOC'23 contributor and would like to do this project

**Comment by theyashwanthsai** [comment]
@Viswaraje This already exists. #114 Check this issue. since we are following the first-come-first-serve policy, we cannot assign you this issue. However, you can create another issue and use the same algorithm on a different dataset.
