### ISSUE TITLE
Building a basic voice assistant

### ISSUE THREAD

**Issue by Venkatapranay** [The-Data-Alchemists-Manipal/MindWave#257]
## 💥 Proposal

I am Pranay, a 3rd year student at GVPCE.
I am a contributor in GSsoc'23 .
I want to work on creating a basic voice assistant  which could convert our speech to text and performs basic tasks such as plays any song from youtube and gives information about a person using wikipedia .
Hope you could assign this to me .

**Comment by theyashwanthsai** [comment]
@Venkatapranay  you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm.py` and link it in the readme of the labeled directory as `algorithm`.
