### ISSUE TITLE
Data analytics : Analysis on udemy cources

### ISSUE THREAD

**Issue by Abhinavcode13** [The-Data-Alchemists-Manipal/MindWave#259]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

It consist of different types of question to do analysis using various python modules like numpy , pandas etc

**Comment by Abhinavcode13** [comment]
Please assign me this @ImranNawar !! asap so I can start working

**Comment by Abhinavcode13** [comment]
@theyashwanthsai please look on this !!

**Comment by Abhinavcode13** [comment]
@khusheekapoor and @theyashwanthsai any update? kindly assign this issue asap

**Comment by theyashwanthsai** [comment]
@Abhinavcode13 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
