### ISSUE TITLE
Eye State Classification using ML

### ISSUE THREAD

**Issue by Rahul-Jain-1** [The-Data-Alchemists-Manipal/MindWave#262]
## 💥 Proposal

Hello!
I am Rahul Jain, a proud contributor of GSSOC 23.  I would like to the contribute to this repository . 

The purpose of EEG (electroencephalography) eye state analysis is to study and understand the brain's electrical activity related to eye movements and eye states, such as open eyes, closed eyes, and blinking.

Dataset Link : [Eye State Classification EEG Dataset](https://www.kaggle.com/datasets/robikscube/eye-state-classification-eeg-dataset)

I want to make this project
so kindly assign me this! : )
@theyashwanthsai  @khusheekapoor

**Comment by theyashwanthsai** [comment]
@Rahul-Jain-1 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
