### ISSUE TITLE
[GSSOC '23] Animal Species Classification using Image Classification

### ISSUE THREAD

**Issue by Shreyg-27** [The-Data-Alchemists-Manipal/MindWave#264]
## 💥 Proposal

Hi! I am Shreya Ganjoo, and I am a GSSOC'23 contributor. I would like to contribute to this repository. 

With the help of deep learning, my objective is to help in the classification of animal species. 
Dataset - https://www.kaggle.com/datasets/utkarshsaxenadn/animal-image-classification-dataset

I have worked on this dataset - https://drive.google.com/drive/folders/1O16B5DZ5SR1Fa_3HHv6NH2_kdcQL059p?usp=sharing
Also uploaded it on Kaggle - https://www.kaggle.com/datasets/shreyaganjoo/animalspecies

**Comment by Shreyg-27** [comment]
Hi @theyashwanthsai! I have raised this issue under gssoc'23.
I would like you to assign this issue to me. 
Thank you.

**Comment by theyashwanthsai** [comment]
@Shreyg-27 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
