### ISSUE TITLE
Loan status prediction using ML

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [The-Data-Alchemists-Manipal/MindWave#269]
## 💥 Proposal
Please Assign this issue to me I want to build a loan prediction system using the ML algorithm SVM in Python.

**Comment by theyashwanthsai** [comment]
@i-am-SnehaChauhan Can you please provide the dataset link which you will be using.

**Comment by Harshita781** [comment]
Please assign this project to me.
Dataset Link: https://www.kaggle.com/datasets/altruistdelhite04/loan-prediction-problem-dataset

**Comment by i-am-SnehaChauhan** [comment]
Hey data set i will be use which is available on kaggle
https://www.kaggle.com/datasets/altruistdelhite04/loan-prediction-problem-dataset

**Comment by i-am-SnehaChauhan** [comment]
Hey @theyashwanthsai please assign this to me.

**Comment by theyashwanthsai** [comment]
@i-am-SnehaChauhan  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by i-am-SnehaChauhan** [comment]
Thank you

**Comment by i-am-SnehaChauhan** [comment]
@theyashwanthsai i will submit the PR today by evening.
