### ISSUE TITLE
Support Vector Machines (SVMs)  on Diabetes Dataset.

### ISSUE THREAD

**Issue by ASHWIN492** [The-Data-Alchemists-Manipal/MindWave#27]
## 💥 Proposal

the datasheet I will used here is :https://www.kaggle.com/datasets/mathchi/diabetes-data-set
I am GSSoC23 contributor assign me this project

**Comment by khusheekapoor** [comment]
@ASHWIN492   - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by lcs2022026** [comment]
@khusheekapoor the dataset i will use is here-https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database
please assign this project to me 
i am GSSOC'23 contributor

**Comment by khusheekapoor** [comment]
@lcs2022026 - could you please open a new issue for this?

**Comment by lcs2022026** [comment]
> @lcs2022026 - could you please open a new issue for this?

ok

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by ASHWIN492** [comment]
@khusheekapoor can you add GSSoC '23 level to.
