### ISSUE TITLE
To add a ChatBot folder in the repository

### ISSUE THREAD

**Issue by Kota-Karthik** [The-Data-Alchemists-Manipal/MindWave#282]
## 💥 Proposal
I want to add a chatbot folder in the repository of Mindwave
This is to help developers, so they can push the chatbot into the folder 
@khusheekapoor @theyashwanthsai 
I am GSSOC'23 contributor 
I want to this project
So kindly assign me this issue : )

**Comment by lcs2022026** [comment]
I want to add a chatbot folder in the repository of Mindwave
This is to help developers, so they can push the chatbot into the folder 
@khusheekapoor @theyashwanthsai 
I am GSSOC'23 contributor 
I want to this project
So kindly assign me this issue : )

**Comment by khusheekapoor** [comment]
Hi, if we have any chatbot projects, we can introduce the folder.
