### ISSUE TITLE
Wine Quality Prediction

### ISSUE THREAD

**Issue by Sindhu-2004** [The-Data-Alchemists-Manipal/MindWave#287]
## 💥 Proposal

Wine Quality Prediction is a system to predict the quality of wine using linear regression

**Comment by Sindhu-2004** [comment]
Please assign me this issue

**Comment by aishani20** [comment]
**PROPOSAL**

I want to contribute on Wine Quality Prediction project, the dataset is available on Kaggle.com website.
Link to the Dataset :- https://www.kaggle.com/code/qusaybtoush1990/wine-quality

I'm contributor of GSSOC'23
I want to work on this issue.
Thankyou.

**Comment by theyashwanthsai** [comment]
@aishani20  @Sindhu-2004  This feature already exists.
