### ISSUE TITLE
Iris Flower Classification

### ISSUE THREAD

**Issue by Sindhu-2004** [The-Data-Alchemists-Manipal/MindWave#288]
## 💥 Proposal

Iris Flower Classification is used to predict the different species of flowers on the length of there petals and sepals.

**Comment by Sindhu-2004** [comment]
Please assign me this issue

**Comment by Sindhu-2004** [comment]
I'm contributor of GSSOC'23

**Comment by theyashwanthsai** [comment]
@Sindhu-2004 Please provide the dataset link and the model which you will be using to train the dataset. Mention it in the description.

**Comment by Sindhu-2004** [comment]
### IRIS FLOWER CLASSIFICATION

**Description**
This project  is used to predict the different species of flowers on the length of there petals and sepals.

The dataset link is:
[Iris (1).csv](https://github.com/The-Data-Alchemists-Manipal/MindWave/files/11644624/Iris.1.csv)

The model used to train the train the data set is:
Decision Tree Classifier (DT)

**Comment by theyashwanthsai** [comment]
@Sindhu-2004  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
