### ISSUE TITLE
healthy food predictor 

### ISSUE THREAD

**Issue by barkhaaroraa** [The-Data-Alchemists-Manipal/MindWave#296]
## 💥 Proposal

a model used to predict whether or not the food that we are going to consume is healthy or not. on the basis of the sugar, fat, proteins, mineral levels 

i am a gssoc'23 contributor could you please assign me this issue

**Comment by theyashwanthsai** [comment]
@barkhaaroraa Please provide the dataset and also mention the model which you will be using. All the best :)

**Comment by barkhaaroraa** [comment]
so i'll be using https://www.kaggle.com/datasets/trolukovich/nutritional-values-for-common-foods-and-products dataset and logical regression model

**Comment by theyashwanthsai** [comment]
@barkhaaroraa cool

**Comment by theyashwanthsai** [comment]
you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
