### ISSUE TITLE
EDA on Obesity Dataset: Understanding Obesity Levels in Mexico, Peru, and Colombia

### ISSUE THREAD

**Issue by affaannn** [The-Data-Alchemists-Manipal/MindWave#302]
Description: This project focuses on performing exploratory data analysis (EDA) on an [obesity dataset](https://archive.ics.uci.edu/ml/machine-learning-databases/00544/). The dataset contains information about individuals from the countries of Mexico, Peru, and Colombia, aged between 14 and 61, with diverse eating habits and physical conditions. The goal of this analysis is to explore the relationship between different lifestyle habits and the types of obesity individuals may have.

Using popular Python libraries such as Pandas, NumPy, Matplotlib, and Seaborn, this project provides comprehensive visualizations and statistical analyses. This EDA aims to uncover insights and patterns within the dataset, shedding light on the factors contributing to obesity levels in the studied population.

**Comment by theyashwanthsai** [comment]
@affaannn - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
