### ISSUE TITLE
Adding a Linear Regression based Vehicle Price Predictor [based on R2 score]

### ISSUE THREAD

**Issue by parridhi** [The-Data-Alchemists-Manipal/MindWave#310]
#### Kindly assign this issue to me.

**Comment by theyashwanthsai** [comment]
@parridhi Please provide the dataset.

**Comment by parridhi** [comment]
#### The dataset was taken from "quikr.com"
#### The one I have attached is a cleaned version of the dataset, which I have used for my model.
[cleancar.csv](https://github.com/The-Data-Alchemists-Manipal/MindWave/files/11646593/cleancar.csv)

**Comment by theyashwanthsai** [comment]
@parridhi - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!  Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by parridhi** [comment]
Sure! Thankyou so much.
