### ISSUE TITLE
[GSSOC'23] Predict the Cancellation of Hotel Booking

### ISSUE THREAD

**Issue by Tanya-1109** [The-Data-Alchemists-Manipal/MindWave#320]
## 💥 Proposal

We will build such a machine learning model that will predict whether a particular hotel booking done by a user is going to be cancelled or not.

**Comment by theyashwanthsai** [comment]
please provide the dataset

**Comment by Tanya-1109** [comment]
Here is the dataset.
[hotel_bookings.csv](https://github.com/The-Data-Alchemists-Manipal/MindWave/files/11724935/hotel_bookings.csv)
Please assign me issue.
