### ISSUE TITLE
[GSSOC'23] LOAN STATUS PREDICTION 

### ISSUE THREAD

**Issue by sahaycodes** [The-Data-Alchemists-Manipal/MindWave#322]
## 💥 LOAN STATUS PREDICTION ML MODEL 

Creation of a ML MODEL which will predict the LOAN STATUS for customers . 
Using an extensive dataset - with applying various Data Pre-processing techniques + adding and using various ML algorithms + models to get the best results. 

Therefore, kindly assign this issue to me.

**Comment by khusheekapoor** [comment]
Hi, we have a similar issue #269. Hence, we cannot assign you this issue.
