### ISSUE TITLE
Fake / Real Logo Detection 

### ISSUE THREAD

**Issue by Shreyg-27** [The-Data-Alchemists-Manipal/MindWave#325]
## 💥 Proposal

So, this machine learning model will help in detecting whether a logo is fake or real.

**Comment by khusheekapoor** [comment]
@Shreyg-27  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
