### ISSUE TITLE
[GSSOC'23] ANIME RECOMMENDATION 

### ISSUE THREAD

**Issue by sahaycodes** [The-Data-Alchemists-Manipal/MindWave#326]
## 💥 CREATION OF AN ANIME RECOMMENDATION SYSTEM

Creating a clear and Concise - Anime Recommendation System using Python and it's Libraries. In this project - Data Cleaning 
,Data Pre-Processing and various other techniques would be used to get appropriate recommendations.

Dataset-https://www.kaggle.com/datasets/brunobacelardc/myanimelist-top-1000-anime
 Therefore, Kindly assign this issue to me.

**Comment by sahaycodes** [comment]
Could you guys ...please review this issue .

**Comment by impeccable16** [comment]
Hi , I would like to work on this issue.

**Comment by sahaycodes** [comment]
@khusheekapoor @theyashwanthsai 
Kindly assign me this issue because it has been quite few days since I posted the issue. Waiting for your response

**Comment by AnishSingh5665** [comment]
I want to contribute but it in GSSOC23

**Comment by khusheekapoor** [comment]
@sahaycodes  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
