### ISSUE TITLE
Naive Bayes on Titanic Dataset

### ISSUE THREAD

**Issue by Harikaraja** [The-Data-Alchemists-Manipal/MindWave#327]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

I want to implement Naive Bayes algorithm from scratch in Python without any SK-learn functions for titanic dataset . This implementation includes Data pre-processing , Visualization of final results , And also Normalization . I would ignore all the irrelevant attributes and would only consider the required and necessary features from the dataset

**Comment by khusheekapoor** [comment]
Hi, we have a similar issue. Hence, we cannot assign you this issue.
