### ISSUE TITLE
Twitter Sentiment Analysis

### ISSUE THREAD

**Issue by mehak1309** [The-Data-Alchemists-Manipal/MindWave#329]
## 💥 Proposal

My name is Mehak. I am a third year student studying BS in Data Science and Applications at Indian Institute of Technology, Madras. I am a GSSOC contributor. I want to work on a project related to natural language processing. I want to classify tweets.

**Comment by priyanka-deshmukh8** [comment]
Hello , I am Priyanka Deshmukh, Final year Student of Mathematics and Computing at Madhav Institute of Technology and Science Gwalior. I am GSSOC contributor and I implemented Sentiment analysis in one of my  twitter Clone Project . I want to solve this issue. Please assign it to me .
Thank you for considering this proposal.

**Comment by impeccable16** [comment]
Hi , I would like to work on this issue.

**Comment by khusheekapoor** [comment]
Hi, we have a similar issue. Hence, we cannot assign you this issue.
