### ISSUE TITLE
Add the black linter workflow 

### ISSUE THREAD

**Issue by metabiswadeep** [The-Data-Alchemists-Manipal/MindWave#330]
Add the black linter workflow to ensure proper and uniform linting of the code. As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using GitHub actions.

I would like to work on this project as a part of GSSoC 23. Please assign this issue to me.

**Comment by khusheekapoor** [comment]
@metabiswadeep  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!
