### ISSUE TITLE
Book Recommedation Model

### ISSUE THREAD

**Issue by shruti-2412** [The-Data-Alchemists-Manipal/MindWave#332]
## 💥 Proposal

To create a book recommendation system that recommends the user books based on his/her previous readings and also recommends the top 50 books based on their rating by other users. Also, create a UI for the same using Flask framework.

Algorithm used- Collaborating filtering using cosine similarity

Dataset link: https://www.kaggle.com/datasets/saurabhbagchi/books-dataset

**Comment by impeccable16** [comment]
Hi , I would like to work on this issue.

**Comment by khusheekapoor** [comment]
@shruti-2412  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
