### ISSUE TITLE
Real/Fake job posting prediction

### ISSUE THREAD

**Issue by Kota-Karthik** [The-Data-Alchemists-Manipal/MindWave#334]
## 💥 Proposal
I want to make a model that predicts whether a job posting is real or fake 
I am gonna make the model using NLP ,mainly Bert
the dataset I am gonna use is :-https://www.kaggle.com/datasets/shivamb/real-or-fake-fake-jobposting-prediction

**Comment by lcs2022026** [comment]
@khusheekapoor @theyashwanthsai 
I am interested in doing this issue 
so kindly assign this to me 
Thank you : )

**Comment by impeccable16** [comment]
Hi , I would like to work on this issue.

**Comment by AnishSingh5665** [comment]
I like to contribute it under GSSOC23.

**Comment by khusheekapoor** [comment]
@lcs2022026 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
