### ISSUE TITLE
add readme badges

### ISSUE THREAD

**Issue by S-ishita** [The-Data-Alchemists-Manipal/MindWave#34]
## 💥 Proposal
I want to add readme badges .Please assign this issue to me under GSSOC
![badges](https://github.com/The-Data-Alchemists-Manipal/MindWave/assets/104543751/bcc475e0-de31-4b86-a1da-eea90c421f5f)

**Comment by khusheekapoor** [comment]
@S-ishita  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!
