### ISSUE TITLE
Algorithm implementation from scratch

### ISSUE THREAD

**Issue by SakshiRathi77** [The-Data-Alchemists-Manipal/MindWave#342]
## 💥 Proposal
My name is Sakshi Rathi, I am ML Enthusiast and have recently learned to implement all algorithms from scratch. As this repository aims to help beginners to give them insight into Data Science. Therefore I aim to create 4 inpyb files with models including linear regression, logistic regression, lasso regression, decision tree with diagrams, mathematical derivation, and complete documented intuition behind them .So please assign me this task under GSSOC.

**Comment by SakshiRathi77** [comment]
I am thinking to use seaborn bydefault dataset like iris and titanic to keep it simple

**Comment by khusheekapoor** [comment]
Hi, we already have many such issues. Hence, we cannot assign you this issue.
