### ISSUE TITLE
Add a new project under the Reinforcement learning title

### ISSUE THREAD

**Issue by tanujbordikar** [The-Data-Alchemists-Manipal/MindWave#345]
## 💥 Proposal

Hello I am a GSSOC'23 contributor and wanted to work on this issue.
**Cart Pole Balance using reinforcement learning:**
DQN can be used as a reinforcement learning algorithm to train an agent to balance a pole on a cart. The goal is to keep the pole upright by moving the cart left or right.
DQN stands for Deep-Q network which combines elements of both deep learning and Q-learning.

**Comment by khusheekapoor** [comment]
@tanujbordikar  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
