### ISSUE TITLE
License Plate Number Detection

### ISSUE THREAD

**Issue by Tisha6661** [The-Data-Alchemists-Manipal/MindWave#353]
## 💥 Proposal
As an active member of GSSOC 23, and working in OpenCV technology, i would love to implement the license plate detection feature in this project, with the actual time, plate image and other details. It would be a auto parking system.

So please assign me this task.

**Comment by khusheekapoor** [comment]
@Tisha6661 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by Tisha6661** [comment]
@khusheekapoor the pull request has been created for the project, please verify it.

**Comment by Tisha6661** [comment]
Here are a few screenshots-
[
![image](https://github.com/The-Data-Alchemists-Manipal/MindWave/assets/98682478/8d7c3e4e-5074-41f4-948d-9af36248d661)
](url)

[
![image](https://github.com/The-Data-Alchemists-Manipal/MindWave/assets/98682478/4a034d27-06b6-407f-8bda-b108f3c5dfe3)
](url)

**Comment by Tisha6661** [comment]
@khusheekapoor the changes have been made for the project, please verify it.

**Comment by Tisha6661** [comment]
Please verify it @khusheekapoor , and inform if any more updates required.
