### ISSUE TITLE
Apply NLP, on restaurant reviews

### ISSUE THREAD

**Issue by Tisha6661** [The-Data-Alchemists-Manipal/MindWave#354]
## 💥 Proposal

As an active member of GSSOC 23, I would like to implement NLP technique on restaurant reviews, implying that the review is a positive or negative review. It would help to improve restaurant management, food, and other organization.

So please assign me this task.

**Comment by khusheekapoor** [comment]
Hi, we have a similar issue (#339). Hence, we won't be able to assign you this.
