### ISSUE TITLE
Virtual Drag and Drop

### ISSUE THREAD

**Issue by dishamodi0910** [The-Data-Alchemists-Manipal/MindWave#355]
## 💥 Proposal
It is a virtual drag-and-drop built using Computer Vision and Artificial Intelligence.

**Comment by dishamodi0910** [comment]
Please assign it to me under GSSOC23!

**Comment by khusheekapoor** [comment]
@dishamodi0910 - please elaborate more.

**Comment by dishamodi0910** [comment]
Basically, we have many upload functions to perform in our day-to-day life, be it uploading pictures or uploading files, we need them very frequently. So it will build a virtual drag and drop system(using OpenCV under Image Processing).

**Comment by khusheekapoor** [comment]
@dishamodi0910   - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
