### ISSUE TITLE
[GSSOC '23] : Word Embedding Using Pytorch

### ISSUE THREAD

**Issue by sujanrupu** [The-Data-Alchemists-Manipal/MindWave#356]
## 💥 Proposal
Word Embeddings in NLP is a technique where individual words are represented as real-valued vectors in a lower-dimensional space and captures inter-word semantics. Each word is represented by a real-valued vector with tens or hundreds of dimensions.
## Feature:
In this project I will implement it using the python **pytorch library**.
## Specification:

- Both N gram and CBOW model will be implemented
- Word similarity will be matched in the context of vectorization

**Comment by sujanrupu** [comment]
@khusheekapoor please assign me this issue under GSSOC '23.

**Comment by khusheekapoor** [comment]
@sujanrupu - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
