### ISSUE TITLE
Earthquake Prediction

### ISSUE THREAD

**Issue by ManaswiKasiraju** [The-Data-Alchemists-Manipal/MindWave#363]
## 💥 Proposal

I would like to predict the magnitude of earthquake based on certain features. I'll create an ML model using Logistic Regression, SVM and Naive Bayes Classification.

**Comment by ManaswiKasiraju** [comment]
[dataset.csv](https://github.com/The-Data-Alchemists-Manipal/MindWave/files/11729754/dataset.csv)

**Comment by Khushibhatnagar** [comment]
I would like to work on this project. Please assign it to me.

**Comment by Akhil-77** [comment]
@Khushibhatnagar You have to create a new issue for yourself if you want to work on a particular project

**Comment by Khushibhatnagar** [comment]
> @Khushibhatnagar You have to create a new issue for yourself if you want to work on a particular project

I wanted to work on Earthquake Prediction so should I create an issue for it or create another new issue other than Earthquake Prediction

**Comment by khusheekapoor** [comment]
@ManaswiKasiraju - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

@Khushibhatnagar - this is first come first serve. Please create an issue on the similar issues for it to be assigned to you.
