### ISSUE TITLE
Red Wine Quality Prediction

### ISSUE THREAD

**Issue by Garvit414** [The-Data-Alchemists-Manipal/MindWave#369]
## 💥 Proposal

I want to add the model for predicting the quality of the red wine using different algos like Linear Regression with multiple variables, Random forest, and many others.
Please assign it to me under GSSOC'23.

**Comment by theyashwanthsai** [comment]
@Garvit414 Please provide the dataset

**Comment by Garvit414** [comment]
I have taken dataset from Kaggle: https://www.kaggle.com/datasets/uciml/red-wine-quality-cortez-et-al-2009

**Comment by Garvit414** [comment]
@theyashwanthsai pls assign it to me.

**Comment by khusheekapoor** [comment]
Hi, we already have an issue on the similar lines (#178). Hence, we cannot assign you this issue.

**Comment by Garvit414** [comment]
Hey @khusheekapoor, Got it but you had given a deadline of 21 days to complete this project to issue #178 and it has been completed. So, if possible assign it to me otherwise I will try to raise some new issue.
