### ISSUE TITLE
Improve the accuracy of diabetes detection by exploring other ML Models.

### ISSUE THREAD

**Issue by AnkitaBarbora** [The-Data-Alchemists-Manipal/MindWave#372]
## 💥 Proposal

The accuracy of the current model (using SVM) in the repository is about 78%. I wish to improve it by testing other Machine Learning models on the dataset (such as adaboost, knn, decision trees etc). 
The Dataset used here is: https://www.kaggle.com/datasets/mathchi/diabetes-data-set and I will be working on it.

**Please assign this task to me under GSSoC'23.**

**Comment by khusheekapoor** [comment]
Hi, we have many similar issues. Hence, we cannot assign you this issue.
