### ISSUE TITLE
Horse Human Prediction

### ISSUE THREAD

**Issue by Anantashayana** [The-Data-Alchemists-Manipal/MindWave#373]
## 💥 Proposal

This model will predict whether a given image is a Horse or a Human. It will be based on Convolutional Neural Networks. I selected a basic project to explain How CNN will work to readers. Each step will be explained thoroughly.

**Comment by khusheekapoor** [comment]
@Anantashayana   - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
