### ISSUE TITLE
Uber Data Analytics Dashboard

### ISSUE THREAD

**Issue by RoopakMallik** [The-Data-Alchemists-Manipal/MindWave#387]
## 💥 Uber Data Analytics Dashboard

A dashboard with precise information about Trip duration, Trip rates, Payment methods used and many other important factors related to an Uber Ride.

**Comment by RoopakMallik** [comment]
> ## 💥 Uber Data Analytics Dashboard
> A dashboard with precise information about Trip duration, Trip rates, Payment methods used and many other important factors related to an Uber Ride.

Please assign me with this issue.

**Comment by khusheekapoor** [comment]
@RoopakMallik - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
