### ISSUE TITLE
Adding dependabot.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [The-Data-Alchemists-Manipal/MindWave#389]
*We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.*

@khusheekapoor  please assign me this issue under gssoc'23.

**Comment by khusheekapoor** [comment]
Hi, I don't think we need this as we have many independent projects and not one single project to find dependencies for.
