### ISSUE TITLE
Adding auto-comment.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [The-Data-Alchemists-Manipal/MindWave#390]
*We need to add an auto-comment.yml that will automatically welcome, greet and provide necessary information to the contributors when they create new issues, PR, and when these will get assigned or merged respectively. This will promote motivation and performance*

@khusheekapoor Please assign me this issue under gssoc'23

**Comment by khusheekapoor** [comment]
@Anshika-Jain02  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!
