### ISSUE TITLE
Book Recommendation using Collaborative Filtering

### ISSUE THREAD

**Issue by Tisha6661** [The-Data-Alchemists-Manipal/MindWave#396]
## 💥 Proposal

Under Gssoc'23 I would like to add the book recommender using machine learning in this project. The goal would be to give the most famous books, book recommendations, and genre based recommendation for the book nerds.

**Comment by khusheekapoor** [comment]
@Tisha6661 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
