### ISSUE TITLE
Image Caption Generator using Deep Learning

### ISSUE THREAD

**Issue by mehak1309** [The-Data-Alchemists-Manipal/MindWave#40]

**Comment by khusheekapoor** [comment]
@mehak1309 - could you please elaborate on the proposal?

**Comment by mehak1309** [comment]
I am Mehak, a 3rd year student at IITM.
I am a contributor in GSsoc'23 .
I want to work on creating caption for every input image. Eg. When a user upload a picture of two girls. The caption might say something like: "The picture shows two girls."
Hope you could assign this to me .

**Comment by khusheekapoor** [comment]
@mehak1309  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `Project.ipynb` and link it in the readme of the labeled directory as `Project`.

**Comment by SAPNILPATEL** [comment]
@mehak1309 I have good experience in the field of Image Captioning. So, if you want we can collaborate and develop the project with great accuracy and less ambiguity in Image Captioning.

**Comment by mehak1309** [comment]
@SAPNILPATEL I am happy to collaborate. You can join.

**Comment by SAPNILPATEL** [comment]
@khusheekapoor  can you please assign the same task to me as well?

**Comment by mehak1309** [comment]
@SAPNILPATEL You can directly contribute to the repo. Please let me know if you have any questions.

**Comment by SAPNILPATEL** [comment]
ok
