### ISSUE TITLE
Forecasting Product Sales using Time Series

### ISSUE THREAD

**Issue by ayush-09** [The-Data-Alchemists-Manipal/MindWave#400]
## 💥 Proposal

The code provided is an implementation of time series techniques to analyze and forecast product sales. The code performs the following steps:

Data cleaning and preprocessing: The dataset containing monthly product sales is loaded and cleaned by dropping unnecessary rows and renaming columns.
Data visualization: The sales data is plotted to visualize the underlying patterns and seasonality.
Stationarity testing: The Augmented Dickey-Fuller (ADF) test is used to check the stationarity of the sales data.
Differencing: If the data is found to be non-stationary, differencing is applied to make it stationary.
Autocorrelation and Partial Autocorrelation analysis: ACF and PACF plots are generated to identify the optimal parameters for the ARIMA model.
Model fitting and forecasting: An ARIMA model is fitted to the sales data, and future sales are forecasted using the model.
Future projections: Future sales are projected for the next 24 months.

**Comment by khusheekapoor** [comment]
@ayush-09  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by ayush-09** [comment]
@khusheekapoor Please review this PR
