### ISSUE TITLE
[GSSoC23] : Gesture Volume Control

### ISSUE THREAD

**Issue by dishamodi0910** [The-Data-Alchemists-Manipal/MindWave#401]
## 💥 Proposal

It is a project that falls under Image Processing using OpenCV. It allows the user to control the system volume using our gestures.

Tech Stack : OpenCV, Python

**Comment by dishamodi0910** [comment]
Please assign me this issue under GSSOC23.

**Comment by khusheekapoor** [comment]
Please tell us which dataset you will be using.

**Comment by dishamodi0910** [comment]
Okay, thank you for informing.
Am closing it as it's already done.
