### ISSUE TITLE
Additions in Issue Template

### ISSUE THREAD

**Issue by Anshika-Jain02** [The-Data-Alchemists-Manipal/MindWave#403]
## Description:

*I noticed that the repository does not have an appropriate issue template.*

*Issue Template: I want to add  some more points to your issue template like feature request, styling changes, documentation, etc*

Please assign this issue to me under Gssoc'23 @khusheekapoor

**Comment by khusheekapoor** [comment]
@Anshika-Jain02 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!

**Comment by Akhil-77** [comment]
Hey, @Anshika-Jain02 you can also update the base README.md file. It doesn't show all the contributors in last section :)

**Comment by Akhil-77** [comment]
@Anshika-Jain02 yes I think you can
