### ISSUE TITLE
Diabetes Detection

### ISSUE THREAD

**Issue by bhavyanarnoli** [The-Data-Alchemists-Manipal/MindWave#404]
## 💥 Proposal
# Description

https://www.kaggle.com/datasets/akshaydattatraykhare/diabetes-dataset?resource=download
From the data set in the (.csv) File We can find several variables, some of them are independent
(several medical predictor variables) and only one target dependent variable (Outcome). These are the given factors which can affect the outcome of diabetes which is (1/0) .
Pregnancies | Glucose | BloodPressure | SkinThickness | Insulin | BMI | DiabetesPedigreeFunction | Age | Outcome

# Scope
This dataset is originally from the National Institute of Diabetes and Digestive and Kidney
Diseases. The objective of the dataset is to diagnostically predict whether a patient has diabetes,
based on certain diagnostic measurements included in the dataset. Several constraints were placed
on the selection of these instances from a larger database. In particular, all patients here are females
at least 21 years old of Pima Indian heritage.2
From the data set in the (.csv) File We can find several variables, some of them are independent
(several medical predictor variables) and only one target dependent variable (Outcome)

# Timeline
Start time: whenever assigned
for atleast trying Logistic Regression ,Random Forest , Support Vector Machines (SVM) , Naive Bayes.
will write the accuracy from all and the f1 score obtain to make it more precise

**Comment by bhavyanarnoli** [comment]
@khusheekapoor  pls assign to me

**Comment by khusheekapoor** [comment]
Hi, we have similar issues. Hence, we cannot assign you this one.
