### ISSUE TITLE
Micro Organism Image Classification

### ISSUE THREAD

**Issue by Kota-Karthik** [The-Data-Alchemists-Manipal/MindWave#405]
## 💥 Proposal
I want to make a model that predicts the class of a Micro-organism
I am gonna make this model using CNN 
the dataset i am gonna use is:-https://www.kaggle.com/datasets/mdwaquarazam/microorganism-image-classification
@khusheekapoor @theyashwanthsai 
I am interested in doing this project 
So kindly assign me this issue 
Thank You: )

**Comment by Kota-Karthik** [comment]
@khusheekapoor @theyashwanthsai 
I am interested in doing this project 
So kindly assign me this issue 
Thank You: )

**Comment by khusheekapoor** [comment]
@Kota-Karthik - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
