### ISSUE TITLE
[Documentation Enhancement] Adding about Image Processing in Documentation

### ISSUE THREAD

**Issue by dishamodi0910** [The-Data-Alchemists-Manipal/MindWave#407]
## 💥 Proposal

A new category was introduced which is image processing, but the readme file is missing information about it.

I would like to add that. Please assign me this issue.

**Comment by khusheekapoor** [comment]
@dishamodi0910 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!
