### ISSUE TITLE
Cardiovascular Disease Prediction

### ISSUE THREAD

**Issue by Garvit414** [The-Data-Alchemists-Manipal/MindWave#413]
## 💥 Proposal

I want to add a notebook that predict whether a person is suffering from cardiovascular disease or not.
I will use this dataset:
https://www.kaggle.com/datasets/sulianova/cardiovascular-disease-dataset

**Comment by khusheekapoor** [comment]
Hi, we have many similar issues. Hence, we cannot assign you this one.
