### ISSUE TITLE
Analysis of Movies earning against movie budget

### ISSUE THREAD

**Issue by arinjain373** [The-Data-Alchemists-Manipal/MindWave#417]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
Spending more money on movie  production can give you good returns or not. To answer this question I want to do a analysis using data set from The-numbers.

Please assign it to me under GSSOC'23 @khusheekapoor 

Thank you

**Comment by impeccable16** [comment]
I want to work on this issue.

**Comment by Error-4-04** [comment]
issue #371 is also  same like yours

**Comment by arinjain373** [comment]
ok @Error-4-04 I will try other issue
