### ISSUE TITLE
SMS Spam detection (Deployed Project)

### ISSUE THREAD

**Issue by shruti-2412** [The-Data-Alchemists-Manipal/MindWave#418]
## 💥 Proposal

An SMS spam detection model for detecting if SMS is spam or not.
Algorithm used: Naive Bayes classifier
I have also deployed the project using streamlit

Dataset link: https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset

**Comment by impeccable16** [comment]
I want to work on this issue

**Comment by khusheekapoor** [comment]
@shruti-2412 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
