### ISSUE TITLE
Covid Detection on X-RAY scans using CNN

### ISSUE THREAD

**Issue by PraNavKumAr01** [The-Data-Alchemists-Manipal/MindWave#42]
## 💥 Proposal

I would like to submit this proposal of building a Covid Detection CNN model that take XRAYS and input and classifies wether its a covid positive or a negative.

Im going to perform data preparation by extracting data from two datasets
https://github.com/ieee8023/covid-chestxray-dataset : for the covid positive xrays
https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia : for negative or normal xrays

i would like to start my contribution by working on this project.

In anticipation of your reply.

**Comment by khusheekapoor** [comment]
@PraNavKumAr01   - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by PraNavKumAr01** [comment]
will get to work right away
Thankyou,

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by khusheekapoor** [comment]
@UditSharma9999  - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue on the similar lines.
