### ISSUE TITLE
Traffic Signs Recognition

### ISSUE THREAD

**Issue by Tisha6661** [The-Data-Alchemists-Manipal/MindWave#422]
## 💥 Proposal

Recognize traffic signs using images, to know the exact meaning of a traffic sign and what it symbolizes, using OpenCV technology.

Record

**Comment by khusheekapoor** [comment]
@Tisha6661 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by Tisha6661** [comment]
@khusheekapoor I have made a pull request regarding this issue, please verify and merge it.
