### ISSUE TITLE
[Machine Learning] : Gold Price Prediction System using Python

### ISSUE THREAD

**Issue by dishamodi0910** [The-Data-Alchemists-Manipal/MindWave#424]
## 💥 Proposal

It will be having a gold price prediction system built using the **Random Forest Regressor** machine learning model.

Dataset link : [Gold Price Dataset - Kaggle](https://www.kaggle.com/datasets/altruistdelhite04/gold-price-data)

**Comment by dishamodi0910** [comment]
@khusheekapoor Please assign me this issue under GSSOC'23

**Comment by khusheekapoor** [comment]
@dishamodi0910 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
