### ISSUE TITLE
Predict Status of Chronic Kidney Disease

### ISSUE THREAD

**Issue by Tanya-1109** [The-Data-Alchemists-Manipal/MindWave#425]
## 💥 Proposal
We will build such a model which will tell us the status of a chronic Kidney Disease. It is a health care use case.

Here is the dataset.
[kidney_disease.csv](https://github.com/The-Data-Alchemists-Manipal/MindWave/files/11782385/kidney_disease.csv)

**Comment by ayush-09** [comment]
Hey! @Tanya-1109  this issue already completed by me name as `Chronic Kidney Disease Prediction`.
If you have better approach apart from this, Explain your approach and algorithm.

**Comment by Tanya-1109** [comment]
Okay!!
