### ISSUE TITLE
AI Tic Tac Toe

### ISSUE THREAD

**Issue by ayush-09** [The-Data-Alchemists-Manipal/MindWave#426]
## 💥 Proposal

The objective of the script is to enhance the Tic Tac Toe game by adding an AI player that provides a challenging gameplay experience for single-player mode.

- AI Player: Implement an intelligent AI player that can make strategic moves in the Tic Tac Toe game.
- Difficulty Levels: Include different difficulty levels for the AI player, allowing users to choose the level of challenge they desire.
- Minimax Algorithm: Utilize the minimax algorithm to optimize the AI player's decision-making process and ensure optimal moves.
- User Interface: Improve the user interface by displaying game status, current player's turn, and the AI player's moves.
- Error Handling: Implement error handling to handle invalid inputs and provide appropriate error messages to the user.
- Replay and Exit: Provide options for the user to replay the game or exit after completing a game.
- By adding these features to the script, it will offer an enhanced and engaging gameplay experience for users, allowing them to enjoy playing Tic Tac Toe against an intelligent AI player.

**Comment by ayush-09** [comment]
@khusheekapoor Please check this issue is this relevant issue for this project..

**Comment by sijalalyy** [comment]
i'm interested in this issue, can you plis assign this to me under gssoc 23?

**Comment by ayush-09** [comment]
@sijalalyy I think issue assign on the basis of the queue

**Comment by khusheekapoor** [comment]
@ayush-09  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
