### ISSUE TITLE
Image classifier web app

### ISSUE THREAD

**Issue by Akhil-77** [The-Data-Alchemists-Manipal/MindWave#433]
## 💥 Proposal

I want to create a deep learning (CNN model) based **web application** which classifies the CIFAR-10 dataset into following classes:
- Cat
- Dog 
- Horse 
- Deer
- Frog 
- Airplane 
- Truck 
- Automobile 
- Ship 
- Bird

I will use CNN model (tensorflow) and flask framework for this.
@theyashwanthsai @khusheekapoor please assign this to me

**Comment by khusheekapoor** [comment]
@Akhil-77  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
