### ISSUE TITLE
Road Lane line detection using OpenCV

### ISSUE THREAD

**Issue by Tisha6661** [The-Data-Alchemists-Manipal/MindWave#435]
## 💥 Proposal

This project is detecting road lane using OpenCV, which is helpful to keep our vehicle on track. It would help in avoiding traffic and road accidents.

Under GSSOC'23, please assign me this task.

**Comment by khusheekapoor** [comment]
@tisha- you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by Tisha6661** [comment]
@khusheekapoor I have created a pull request for this project, please verify it and merge it.

**Comment by Tisha6661** [comment]
Also Please check these pull requests I've made long ago but are not merged, please inform if any updates are required in them @khusheekapoor #397 , #438
