### ISSUE TITLE
Face Detection using OpenCV

### ISSUE THREAD

**Issue by Tisha6661** [The-Data-Alchemists-Manipal/MindWave#437]
## 💥 Proposal

A program to detect faces moving in and out of video frames using OpenCV. It is a program that detects the face and calculate the amount of time it was out of the webcam and then store the time in a csv file.

**Comment by khusheekapoor** [comment]
@Tisha6661  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by Tisha6661** [comment]
@khusheekapoor I have created a pull request regarding this task, please verify it.
