### ISSUE TITLE
KNN image classifier

### ISSUE THREAD

**Issue by Akhil-77** [The-Data-Alchemists-Manipal/MindWave#445]
## 💥 Proposal

I want to build a KNN model based image classifier to classify the forest vs desert dataset on Kaggle 

dataset link - https://www.kaggle.com/datasets/akhiljethwa/forest-vs-desert

**Comment by khusheekapoor** [comment]
@Akhil-77 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
