### ISSUE TITLE
Music Recommendation System

### ISSUE THREAD

**Issue by Sindhu-2004** [The-Data-Alchemists-Manipal/MindWave#448]
## 💥 Proposal

This project is used to build music recommendation system using spotify dataset.

**Comment by amankumar100** [comment]
Please assign me this issue, I will resolve it.
I have a clear idea of it.

**Comment by impeccable16** [comment]
I want to work on this issue

**Comment by Sindhu-2004** [comment]
I am the contributor of GSSOC'23

**Comment by khusheekapoor** [comment]
Hi, we have several issues on the similar issues. Hence, we cannot assign you this issue.
