### ISSUE TITLE
Music genre classification and hypertuning it

### ISSUE THREAD

**Issue by Kota-Karthik** [The-Data-Alchemists-Manipal/MindWave#45]
to create a music genre classifier and hypertune it to make its best version
@khusheekapoor

**Comment by khusheekapoor** [comment]
@lcs2022026   - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by lcs2022026** [comment]
i would like to work on this issue 
i am GSSOC'23 contributor
the dataset i would like to use is :-https://www.kaggle.com/datasets/andradaolteanu/gtzan-dataset-music-genre-classification
