### ISSUE TITLE
Medical Insurance cost prediction

### ISSUE THREAD

**Issue by itsdebartha** [The-Data-Alchemists-Manipal/MindWave#451]
## 💥 Proposal
I am a GSSoC'23 contributor and I want to implement the medical insurance cost prediction using machine learning in **The Julia Programming Language**. The dataset is available at: https://www.kaggle.com/datasets/mirichoi0218/insurance

I understand that #18 and #65 wanted to deal with the same thing, however, both of them were closed and none of them were implemented. Further, this would make an excellent project for Julia.
(A clear and concise description of what the proposal is.)

@khusheekapoor kindly look at this...

**Comment by impeccable16** [comment]
I want to work on this issue

**Comment by khusheekapoor** [comment]
@itsdebartha   - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset_language.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset - language`.

**Comment by khusheekapoor** [comment]
@impeccable16 - we assign issues on a first come first serve basis.
