### ISSUE TITLE
Food Detection

### ISSUE THREAD

**Issue by karthikbhandary2** [The-Data-Alchemists-Manipal/MindWave#452]
## 💥 Proposal

I would like to make a food detector using Pytorch which takes in an image of a food and gives its name.

**Comment by khusheekapoor** [comment]
@karthikbhandary2 - please provide the dataset.

**Comment by karthikbhandary2** [comment]
https://www.kaggle.com/datasets/dansbecker/food-101

**Comment by khusheekapoor** [comment]
@karthikbhandary2 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
