### ISSUE TITLE
EDA of Udemy data

### ISSUE THREAD

**Issue by karthikbhandary2** [The-Data-Alchemists-Manipal/MindWave#453]
## 💥 Proposal

I have seen that there is not EDA done on the Udemy data. I would like to do it. Please assign me this task.

**Comment by khusheekapoor** [comment]
@karthikbhandary2 - please provide the dataset.

**Comment by karthikbhandary2** [comment]
It is the data set that is in the data analytics folder: https://github.com/The-Data-Alchemists-Manipal/MindWave/tree/main/Data%20Analytics/Udemy%20courses_analysis

**Comment by karthikbhandary2** [comment]
ok
