### ISSUE TITLE
Traffic-Signal-Violation-Detection-System

### ISSUE THREAD

**Issue by Killer2OP** [The-Data-Alchemists-Manipal/MindWave#455]
## 💥 Proposal
The goal of the project is to automate the traffic signal violation detection system and make it easy for the traffic police department to monitor the traffic and take action against the violated vehicle owner in a fast and efficient way. Detecting and tracking the vehicle and their activities accurately is the main priority of the system.

**Comment by impeccable16** [comment]
Hi I want to work on this issue

**Comment by khusheekapoor** [comment]
@Killer2OP - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
