### ISSUE TITLE
MNIST Digit recognition using SVM

### ISSUE THREAD

**Issue by lakshmishreea122003** [The-Data-Alchemists-Manipal/MindWave#457]
## 💥 Proposal
Dataset = Mnist dataset
Model = SVM
Description = Develop a model using Support Vector Machine which correctly classifies the handwritten digits from 0-9 based on the pixel values given as features. Thus, this is a 10-class classification problem.

**Comment by lakshmishreea122003** [comment]
I wish to work on this issue as a GSSoC contributor. Kindly assign it to me.

**Comment by khusheekapoor** [comment]
Hi, we have several issues on the similar lines. Hence, we cannot assign you this issue.
