### ISSUE TITLE
Fake news Detection

### ISSUE THREAD

**Issue by Sindhu-2004** [The-Data-Alchemists-Manipal/MindWave#459]
## 💥 Proposal

This model is trained in such a way to predict the fake news with best accuracy.

**Comment by sijalalyy** [comment]
can you plis assign this issue to me under gssoc 23?

**Comment by Simran211103** [comment]
I request you to please assign me this issue under gssoc 2023

**Comment by khusheekapoor** [comment]
Hi, we have several issues on the similar lines. Hence, we cannot assign you this issue.
