### ISSUE TITLE
obesity classification

### ISSUE THREAD

**Issue by lcs2022026** [The-Data-Alchemists-Manipal/MindWave#46]
@khusheekapoor 
i would like to work on this issue
this will classify obesity into different categories 
the dataset i am gonna use is :- https://www.kaggle.com/datasets/sujithmandala/obesity-classification-dataset?select=Obesity+Classification.csv

**Comment by lcs2022026** [comment]
@khusheekapoor
i would like to work on this issue
this will classify obesity into different categories
the dataset i am gonna use is :- https://www.kaggle.com/datasets/sujithmandala/obesity-classification-dataset?select=Obesity+Classification.csv
@khusheekapoor

**Comment by Saiesh-Agre** [comment]
Hello @khusheekapoor 
I would like to work on this issue.
I will implement SVM, KNN and other classification algorithms to test the accuracy, and will select the one which is more accurate, and is good at generalization.

**Comment by tushtithakur** [comment]
Hi, I would like to contribute o this issue. I'm eager to enhance MindWave with an obesity classification model using Python and ML. 
Kindly consider assigning me this task. Looking forward to collaborate.

**Comment by tushtithakur** [comment]
Hi, I'm super excited to be a part of the obesity classification project and contribute using ML models like SVM, Random Forest, and Neural Networks. With my experience in data science and ML, I'm confident in creating accurate models. 
I'd be grateful if you could assign me this task so we can collaborate and make an impact on obesity classification.

**Comment by khusheekapoor** [comment]
@lcs2022026   - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

@Saiesh-Agre @tushtithakur  - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue on the similar lines.

**Comment by lcs2022026** [comment]
> @lcs2022026   - which algorithms will you be using?
> 
> SVM , logistic, Random Forest and I would pick the best one out of it

**Comment by lcs2022026** [comment]
@khusheekapoor 
I had completed my issue assigned to me - obesity classification
What I have to do next

**Comment by khusheekapoor** [comment]
@lcs2022026 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by lcs2022026** [comment]
@khusheekapoor 
I had made a pull request 
kindly have a look at it 
and then merge it to main branch
