### ISSUE TITLE
Anime image classification

### ISSUE THREAD

**Issue by Kota-Karthik** [The-Data-Alchemists-Manipal/MindWave#462]
## 💥 Proposal
I want to make a model that predicts the anime name by seeing its image
I will make this model using CNN
the dataset i am gonna use is:- https://www.kaggle.com/datasets/diraizel/anime-images-dataset/code
@khusheekapoor @theyashwanthsai 
I am interested in doing this project so kindly assign me this 
Thank You : )

**Comment by Kota-Karthik** [comment]
@khusheekapoor @theyashwanthsai 
I am interested in doing this project so kindly assign me this 
Thank You : )

**Comment by khusheekapoor** [comment]
@Kota-Karthik - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
