### ISSUE TITLE
Eye Detection Using opencv

### ISSUE THREAD

**Issue by karthikbhandary2** [The-Data-Alchemists-Manipal/MindWave#463]
## 💥 Proposal

In this project, I am going to use open cv to detect eyes in the image/video.

**Comment by khusheekapoor** [comment]
@YB73  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by karthikbhandary2** [comment]
Can I submit this as a .py file?

**Comment by khusheekapoor** [comment]
Sure @karthikbhandary2
