### ISSUE TITLE
[Image Processing] : AI based Virtual Mouse

### ISSUE THREAD

**Issue by dishamodi0910** [The-Data-Alchemists-Manipal/MindWave#464]
## 💥 Proposal

The AI-based virtual mouse will basically be used to perform actions on the screen like clicking, dropping, and dragging without the use of the mechanical mouse.
Tech Stack used: OpenCV, CVZone, and MediaPipe

It contains no dataset.

**Comment by dishamodi0910** [comment]
@khusheekapoor Please assign me this issue under GSSoC23

**Comment by khusheekapoor** [comment]
@YB73  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!
