### ISSUE TITLE
[Deployed Projects] : Adding Diabetes Prediction System

### ISSUE THREAD

**Issue by dishamodi0910** [The-Data-Alchemists-Manipal/MindWave#465]
## 💥 Proposal

It will contain the deployment of a Diabetes Prediction System as Public API using FastAPI in Google Collab

**Comment by dishamodi0910** [comment]
@khusheekapoor Please assign me this issue under GSSoC23

**Comment by khusheekapoor** [comment]
Hi, we have several issues on the similar lines. Hence, we cannot assign you this issue.
