### ISSUE TITLE
Restaurant Revenue Prediction

### ISSUE THREAD

**Issue by AnkitaBarbora** [The-Data-Alchemists-Manipal/MindWave#467]
## 💥 Proposal
The objective of this project is to develop a machine learning model that predicts restaurant revenue based on various factors. The accurate prediction of revenue can help restaurant owners and managers make informed decisions regarding pricing strategies, resource allocation, and overall business planning. 
The dataset to be used is https://www.kaggle.com/competitions/restaurant-revenue-prediction/data

**Please assign this task to me under GSSoC'23.**

**Comment by khusheekapoor** [comment]
Hi, we have several issues on the similar lines. Hence, we cannot assign you this issue.
