### ISSUE TITLE
sentiment analysis tweets of twitter

### ISSUE THREAD

**Issue by Sushilverma002** [The-Data-Alchemists-Manipal/MindWave#468]
## 💥 Proposal

i would like to do project on sentiment analysis of the tweets of twitter
this i will checking the unwanted and resist tweet among the data set of around 35k using LOGISTIC REGRESSION.
I  will provide you with that data set.
i will be using python libraries like numpy , panda , matplot ,etc .
and i will doing in jupyter notebook.

**Comment by khusheekapoor** [comment]
Hi, we have several issues on the similar lines. Hence, we cannot assign you this issue.
