### ISSUE TITLE
[GSSOC'23] Water Quality Prediction Model

### ISSUE THREAD

**Issue by sahaycodes** [The-Data-Alchemists-Manipal/MindWave#469]
## 💥 Water Quality Prediction Model - GSSOC'23

As we know, Water is an important part of everyone's lives. Therefore, its important to know the quality of Water being used.
In this project, we will apply Machine Learning concepts like-EDA, Data Visualization and Model Building

Dataset - https://www.kaggle.com/datasets/shreyanshverma27/water-quality-testing

Therefore, kindly assign this issue to me

**Comment by sahaycodes** [comment]
@khusheekapoor , kindly assign this issue to me.

**Comment by khusheekapoor** [comment]
@sahaycodes  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
