### ISSUE TITLE
Edge Detection using OpenCV [GSSOC 23]

### ISSUE THREAD

**Issue by Mochoye** [The-Data-Alchemists-Manipal/MindWave#471]
## 💥 Proposal

Apply Canny Edge Detection to Images
Tweak and Tune Detection Parameters to improve Results
Export final detections

Expected behavior
It can detect edges which can be used in identifying number plates

**Comment by khusheekapoor** [comment]
@Mochoye - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
