### ISSUE TITLE
Drowziness Detection [GSSOC'23]

### ISSUE THREAD

**Issue by Mochoye** [The-Data-Alchemists-Manipal/MindWave#472]
## 💥 Proposal

Will be implementing Drowsiness Detection using YOLO. Making detections and checking the real time performance

**Comment by khusheekapoor** [comment]
@Mochoye  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
