### ISSUE TITLE
Predict Prices of Airline Ticket

### ISSUE THREAD

**Issue by Tanya-1109** [The-Data-Alchemists-Manipal/MindWave#473]
## 💥 Proposal

We will build such a model which will predict the price of an airline.

[Dataset.xlsx](https://github.com/The-Data-Alchemists-Manipal/MindWave/files/11849844/Data_Train.xlsx)
Here is the dataset.

**Comment by ArunMunagala7** [comment]
Could I work on this?

**Comment by khusheekapoor** [comment]
@Tanya-1109  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

@ArunMunagala7 - we work on a first come first serve basis. You can raise an issue on the similar lines.

**Comment by megha-ahirwar** [comment]
I want to work on this.
