### ISSUE TITLE
[Image Processing] : Zoom Gesture

### ISSUE THREAD

**Issue by dishamodi0910** [The-Data-Alchemists-Manipal/MindWave#474]
## 💥 Proposal

It is a basic virtual zoom in - zoom out system built using OpenCV, cv zone, and media pipe.
It will be allowing to perform zoom gestures of objects on screen. 

**It contains no dataset**

**Comment by dishamodi0910** [comment]
Please assign me this issue. @khusheekapoor

**Comment by khusheekapoor** [comment]
@dishamodi0910  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
