### ISSUE TITLE
Diabetes Prediction using scikit-learn dataset [GSSOC'23]

### ISSUE THREAD

**Issue by adityabachu** [The-Data-Alchemists-Manipal/MindWave#480]
## 💥 Proposal

I would like to add a new project in the ML section that is Diabetes prediction using logistic Regression i will be using scikit-learn dataset

**Comment by msanaul** [comment]
Please assign this project to me. I'll do that.

**Comment by khusheekapoor** [comment]
Hi, we have many issues on the similar lines. Hence, we cannot assign you this issue.
