### ISSUE TITLE
Heart disease prediction in alternative Language (Python) [GSSOC'23]

### ISSUE THREAD

**Issue by Pritamstudent** [The-Data-Alchemists-Manipal/MindWave#483]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
I would like to contribute by adding the machine learning model in alternative language i.e. Python .  It will involve all the steps on how to analyze and train a machine learning model along with a predictive system.

**Comment by msanaul** [comment]
I want to do this. Please assign it to me.

**Comment by khusheekapoor** [comment]
@Pritamstudent - which model will you be using? Also, most ML models in this repo are in Python. 
@msanaul - the issues are assigned in first-come-first-serve basis.

**Comment by msanaul** [comment]
If by any chance this is to be assigned to me, then I'll be using logistic regression for the same.

**Comment by Pritamstudent** [comment]
Actually Heart disease prediction is in R so I wanted to do based on Python. Moreover I will be using Logistic regression for it with stratified sampling. @khusheekapoor

**Comment by Pritamstudent** [comment]
Any update?

**Comment by khusheekapoor** [comment]
Hi, we have many similar issues. Hence, we cannot assign you this issue.
