### ISSUE TITLE
LightGBM model on Netflix Movies and TV Shows

### ISSUE THREAD

**Issue by Shubhra-31** [The-Data-Alchemists-Manipal/MindWave#484]
## 💥 Proposal
LightGBM model applied on "Netflix Movies and TV Shows" and Optuna for hyper parameter tuning.

Dataset-> https://www.kaggle.com/datasets/shivamb/netflix-shows

@khusheekapoor 
@theyashwanthsai

**Comment by khusheekapoor** [comment]
@Shubhra-31 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by Shubhra-31** [comment]
@khusheekapoor @theyashwanthsai could you please add the deep learning label as well ? I have made use of tfidf vectorizer as well on textual data. 
The work is ready.
