### ISSUE TITLE
Face Mask Detection using OpenCV

### ISSUE THREAD

**Issue by Tisha6661** [The-Data-Alchemists-Manipal/MindWave#485]
## 💥 Proposal
To detect whether a person is wearing mask or not, which would be detected using OpenCV. It would be very useful today in the scenario of covid virus, also in hospitals to check all are wearing mask or not.

As an active member of GSSOC'23, please assign me this.

**Comment by khusheekapoor** [comment]
Hi, we already have a similar issue. Hence, we cannot assign you this issue.
