### ISSUE TITLE
Parking Space Detection

### ISSUE THREAD

**Issue by Tisha6661** [The-Data-Alchemists-Manipal/MindWave#486]
## 💥 Proposal
To detect parking space in a parking lot, to park the car. It would be detected using OpenCV. It would be useful in parking areas to check, where one can park a car.

As an active member of GSSOC'23 please assign me this task.

**Comment by khusheekapoor** [comment]
@Tisha6661  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by Tisha6661** [comment]
@khusheekapoor I have created a pull request regarding this task, please verify and merge it.
