### ISSUE TITLE
Document Scanner using OpenCV

### ISSUE THREAD

**Issue by Tisha6661** [The-Data-Alchemists-Manipal/MindWave#487]
## 💥 Proposal
To detect the document using OpenCV, Scan it in color format or greyscale format, and print it in the form of pdf.

As an active GSSOC'23 member, please assign me this task.

**Comment by khusheekapoor** [comment]
@Tisha6661 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by Tisha6661** [comment]
@khusheekapoor I have created a pull request regarding this issue, please verify and merge it.
