### ISSUE TITLE
Drone Detection

### ISSUE THREAD

**Issue by shraddha761** [The-Data-Alchemists-Manipal/MindWave#488]
## 💥 Proposal

Detect drones from input image, video or real-time feed.

Assign this issue to me under GSSOC'23

**Comment by khusheekapoor** [comment]
@shraddha761 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
