### ISSUE TITLE
International-Debt-Statistics 

### ISSUE THREAD

**Issue by shraddha761** [The-Data-Alchemists-Manipal/MindWave#489]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
Using python, I developed a script to download PPG Bilateral Debt data between 2 countries using World Bank API.
Assign this issue to me under GSSOC'23

**Comment by khusheekapoor** [comment]
Hi, can you please elaborate more? is the project just a loader?

**Comment by shraddha761** [comment]
@khusheekapoor In this project collects data of PPG bilateral lending between India and its neighbouring countries which include Bangladesh, Bhutan, Sri Lanka, Nepal, Maldives & Myanmar so basically it wrangled and analysed data from last 20 years of each country individually and visualized the data in form of excel dashboard for easy understanding of lending trend
