### ISSUE TITLE
SMS Spam Classifier Using Naive Bayes and NLTK

### ISSUE THREAD

**Issue by PraNavKumAr01** [The-Data-Alchemists-Manipal/MindWave#49]
## 💥 Proposal

I would like to work on an SMS spam classifier that uses the Naive Bayes model and NLTK to convert text into computer code. Also going to build a Streamlit website for the implementation of the model

I would ask you to assign me this project so that I can start working as soon as possible

In anticipation of your reply

**Comment by khusheekapoor** [comment]
@PraNavKumAr01 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
