### ISSUE TITLE
Show the actual implementation of Linear Regression (What is inside this Linear Regression black box and test it on salary dataset][GSSOC'23]

### ISSUE THREAD

**Issue by Pritamstudent** [The-Data-Alchemists-Manipal/MindWave#490]
I want to show the actual implementation of linear regression without importing it from sklearn and then test it on small data-set

**Comment by khusheekapoor** [comment]
Hi, please link the dataset.

**Comment by khusheekapoor** [comment]
@Pritamstudent - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by Pritamstudent** [comment]
Please check the PR. Thanks.
