### ISSUE TITLE
I want to show the actual implementation of support vector machine classifier without importing it from sklearn and then test it on small data-set . [GSSOC'23]

### ISSUE THREAD

**Issue by Pritamstudent** [The-Data-Alchemists-Manipal/MindWave#492]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
I want to show the actual implementation of linear regression without importing it from sklearn and then test it on small data-set

**Comment by khusheekapoor** [comment]
Hi, we have similar issues. Hence, we cannot assign you this issue.
