### ISSUE TITLE
Neural style transfer using tensorflow

### ISSUE THREAD

**Issue by lakshmishreea122003** [The-Data-Alchemists-Manipal/MindWave#494]
## 💥 Proposal
This project combines the content of one image with the artistic style of another image, creating a new image that preserves the content while adopting the style. I will use a pre-trained convolutional neural network to extract features and optimize the generated image to minimize content and style differences.

**Comment by lakshmishreea122003** [comment]
Kindly assign it to me

**Comment by khusheekapoor** [comment]
Hi, please link the dataset.

**Comment by lakshmishreea122003** [comment]
I have not used any dataset for this project. VGG-19, a 19-layer version of the VGG network has been used in this project. This model has already been trained on the very large ImageNet database and has learned to recognize a variety of low-level features (at the shallower layers) and high-level features (at the deeper layers).
In this project, I have :
- Implemented the neural style transfer algorithm
- Generated novel artistic images using your algorithm
- Define the style cost function for Neural Style Transfer
- Define the content cost function for Neural Style Transfer

**Comment by khusheekapoor** [comment]
@lakshmishreea122003  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm.ipynb` and link it in the readme of the labeled directory as `algorithm`.
