### ISSUE TITLE
Stock market sentiment analysis

### ISSUE THREAD

**Issue by Venkatapranay** [The-Data-Alchemists-Manipal/MindWave#500]
I am pranay, I want to make a model that classifies the stock market analysis as positive or negative feedback

I am gonna make this model using NLP(Natural Language Processing) and Multinomial Naive Bayes algorithm
the dataset I am gonna use is :- https://www.kaggle.com/datasets/yash612/stockmarket-sentiment-dataset
@khusheekapoor 
I am interested in doing this project so kindly assign me this

**Comment by khusheekapoor** [comment]
Hi, we have many similar issues. Hence, we cannot assign you this issue.
