### ISSUE TITLE
Anime Recommendation Generator 

### ISSUE THREAD

**Issue by Mochoye** [The-Data-Alchemists-Manipal/MindWave#502]
### Is your feature request related to a problem? Please describe.

It will be giving me Anime Recommendation. Anime are animated comics which takes inspiration from Manga. Anime are very famous amongst the young generation so creating it will be attractive.

### Describe the solution you'd like

First with the dataset we will be performing EDA and preparing the dataset also visualizing various aspects of the data to gain insights into our anime recommendation problem.

In the second part we will focus on training the recommendation model using the final dataset made in the first part.

Expected behavior
It will be giving me Anime recommendation by Content Based and Item Based recommendation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khusheekapoor** [comment]
Hi, we have a similar issue (#326). Hence, we cannot assign you this issue.
