### ISSUE TITLE
[GSSOC'23]Data Analytics on Game Development Industry

### ISSUE THREAD

**Issue by smty2018** [The-Data-Alchemists-Manipal/MindWave#507]
### Is your feature request related to a problem? Please describe.

By analyzing this data, we can gain insights into player  game popularity, demographics, and patterns .Will do identification of key parameters which drives the growth of a video game and perform a trend analysis showing how the video game industry
has evolved over the course of time. 
dataset: 
[game.xlsx](https://github.com/The-Data-Alchemists-Manipal/MindWave/files/11870832/game.xlsx)

### Describe the solution you'd like

This information can be used to optimize game features, improve user experiences ,etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by smty2018** [comment]
@khusheekapoor Please assign it to me under GSSOC'23

**Comment by khusheekapoor** [comment]
@smty2018 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
