### ISSUE TITLE
Cartoonization of images using OpenCV

### ISSUE THREAD

**Issue by Tisha6661** [The-Data-Alchemists-Manipal/MindWave#514]
### Is your feature request related to a problem? Please describe.

Today everyone is using snapchat, instagram for funny filters. One such filter is converting the image in a cartoon or caricature, is what we can call it. I would like to make such cartoons using OpenCV.

### Describe the solution you'd like

Cartoonization of images, would use OpenCV to make changes to an image and convert it into a cartoon of the person, we also use such avatars now a days. So I would like people to use that.

### Describe alternatives you've considered

There can be colour filters added to the cartoons.

### Additional context

Under GSSOC'23 please assign me this task.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khusheekapoor** [comment]
@Tisha6661 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by Tisha6661** [comment]
@khusheekapoor I have created a pull request regarding this task, please verify and merge it.
