### ISSUE TITLE
[Machine Learning] : Rock vs Mine Prediction

### ISSUE THREAD

**Issue by dishamodi0910** [The-Data-Alchemists-Manipal/MindWave#520]
It will be a logistic regression-based analysis to check whether it's a rock or mine.

The dataset to be used : [dataset](https://www.kaggle.com/datasets/rupakroy/sonarcsv)

**Comment by dishamodi0910** [comment]
Please assign me this issue under GSSoC23 @khusheekapoor

**Comment by khusheekapoor** [comment]
Hi, we have a similar issue. Hence, we cannot assign you this.
