### ISSUE TITLE
[GSSoC'23] Employee Risk Prediction

### ISSUE THREAD

**Issue by manishkumar00208** [The-Data-Alchemists-Manipal/MindWave#523]
### Is your feature request related to a problem? Please describe.

Build a tool that uses data analytics to predict which employees are at risk of leaving a company and suggest retention strategies to prevent them from leaving.

### Describe the solution you'd like

Developed a Machine Learning Model - Logistic Regression that uses data analytics to predict which employees are at risk of leaving a company and suggest retention strategies to prevent them from leaving.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manishkumar00208** [comment]
@khusheekapoor Please assign me this issue!

**Comment by khusheekapoor** [comment]
@manishkumar00208 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by manishkumar00208** [comment]
@khusheekapoor I want to upload my project in Data Analytics section, as it is not a deployed one (web app). So, I request you to change the label to Data Analytics.

**Comment by manishkumar00208** [comment]
@khusheekapoor I've Created a PR for this Issue Adding my project in the Data Analytics Section rather in Deployed Projects section.....! PR #547
