### ISSUE TITLE
Search Engine Recommendation

### ISSUE THREAD

**Issue by shashank1623** [The-Data-Alchemists-Manipal/MindWave#527]
### Is your feature request related to a problem? Please describe.

A search engine content-based recommender system that recommends movies similar to the movie the user likes and analyses the sentiments of the reviews given by the user.

### Describe the solution you'd like

The movies are recommended based on the content of the movie you entered or selected. The main parameters that are considered for the recommendations are the genre, director, and top 3 casts. The details of the movies, such as title, genre, runtime, rating, poster, casts, etc., are fetched from https://www.themoviedb.org/documentation/api . The reviews of each individual movie given by the users are "web-scraped" from the IMDB website with the help of beautifulsoup4 , and the reviews are subjected to sentiment analysis, where the model predicts whether the review is positive or negative.

Data Source : some of the datasets i will be using from kaggle and rest of the data will prepared using web scraping . 

### Additional context

@khusheekapoor Please assing me this issue . So that i can start working on it . 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khusheekapoor** [comment]
@shashank1623 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by shashank1623** [comment]
Ohk not an issue !
