### ISSUE TITLE
[GSSoC'23] Bengaluru House Price Predicton (ML)

### ISSUE THREAD

**Issue by Juhibhojani** [The-Data-Alchemists-Manipal/MindWave#534]
### Is your feature request related to a problem? Please describe.

I want to implement Regression techniques for Bengaluru house price prediction dataset.

Dataset : https://www.kaggle.com/datasets/amitabhajoy/bengaluru-house-price-data
Algorithm : Linear Regression

### Describe the solution you'd like

My major focus for this project will be outlier removal using background knowledge and data visualization technique

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khusheekapoor** [comment]
Hi, we have many similar issues. Hence, we cannot assign you this issue.
