### ISSUE TITLE
[Image Processing] : Virtual Keyboard 

### ISSUE THREAD

**Issue by dishamodi0910** [The-Data-Alchemists-Manipal/MindWave#540]
It is basically a development of virtual keyboard on screen.
It helps one to avoid the usage of mechanical keyboard everywhere.

# How it's helpful?
There is no need to carry the keyboard with you. The virtual keyboard developed with help of OpenCV, CVZone is there to help everywhere you need.

Tech stacks : Python, OpenCV, CVZone and MediaPipe

**Comment by dishamodi0910** [comment]
Please assign me this issue under GSSoC23 @khusheekapoor

**Comment by khusheekapoor** [comment]
@dishamodi0910  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
