### ISSUE TITLE
Sentimental Analysis with 3 models: Logistics Regression, Support Vector Classifier, Naive Bayes (MultinomialNB) .  [GSSOC'23] 

### ISSUE THREAD

**Issue by Pritamstudent** [The-Data-Alchemists-Manipal/MindWave#543]
### Is your feature request related to a problem? Please describe.

I want to do the proper structured sentimental analysis of the twitter data. The model will predict whether the tweets are negative, positive or neutral. The link to the dataset is given below:
[Twitter Data](https://drive.google.com/file/d/1qM7qulCSG6qicsh1NgKf7xxYoCxRCuU6/view?usp=sharing)

Note:  There is one more sentimental analysis project in the repository but it is done on covid data-set and my steps and dataset is different. 

### Describe the solution you'd like

I would like to do the structured text-preprocessing of the data, structure the model and then evaluate the model using accuracy, precision, recall, f1-score.  Then, formulate the confusion matrix. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khusheekapoor** [comment]
Hi, we have many similar issues. Hence, we cannot assign you this one.
