### ISSUE TITLE
Adding ML algorithms with example datasets

### ISSUE THREAD

**Issue by okaditya84** [The-Data-Alchemists-Manipal/MindWave#55]
## 💥 Proposal

I can implement and add all ML algorithms like Linear Regression, Logistic Regression, Random Forest, Support Vector Machine etc.
This will be a easy to understand addition such that any newbie in ML can implement by themselves.

**Comment by tushtithakur** [comment]
Hi, I am very much interested and would like to contribute as a part of @GSSOC'23.
Please assign the task to me. Thank you.

**Comment by khusheekapoor** [comment]
@okaditya84 - which dataset will you be using?

**Comment by okaditya84** [comment]
> @okaditya84 - which dataset will you be using? 

I'll be using boston house prices dataset. It's easy to understand and easy to implement for all the beginners

**Comment by khusheekapoor** [comment]
@okaditya84 - we have multiple issues on the same. Hence, we won't be able to assign you this issue.
