### ISSUE TITLE
Amazon-Product-Length-Prediction-Dataset

### ISSUE THREAD

**Issue by shashank1623** [The-Data-Alchemists-Manipal/MindWave#551]
### Is your feature request related to a problem? Please describe.

The goal is to develop a machine learning model that can predict the length dimension of a product. Product length is crucial for packaging and storing products efficiently in the warehouse. Moreover, in many cases, it is an important attribute that customers use to assess the product size before purchasing. However, measuring the length of a product manually can be time-consuming and error-prone, especially for large catalogs with millions of products.

You will have access to the product title, description, bullet points, product type ID, and product length for 2.2 million products to train and test your submissions. Note that there is some noise in the data.

### Describe the solution you'd like

This problem will solve using NLP with regression .

### Additional context

the datasets is provided by amazon .
@khusheekapoor please assign me this issue .

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khusheekapoor** [comment]
@shashank1623 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
