### ISSUE TITLE
Counting People in a frame using OpenCV

### ISSUE THREAD

**Issue by Tisha6661** [The-Data-Alchemists-Manipal/MindWave#552]
### Is your feature request related to a problem? Please describe.

There are various occasions in which we need to study an image or video. In doing so, first thing we capture is people. What if we can count them automatically coming in and out of a video. It doesn't matter if they are completely in the frame, but any part of there body tells they are present in the frame.

### Describe the solution you'd like

To do so, i would use OpenCV to count the number of people in a frame, using face, body, legs analysis.

### Additional context

Under GSSOC'23 please assign me this task.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khusheekapoor** [comment]
@Tisha6661 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by Tisha6661** [comment]
@khusheekapoor I have created a pull request regarding this, please verify and merge it.
