### ISSUE TITLE
Eye Color Detection

### ISSUE THREAD

**Issue by Tisha6661** [The-Data-Alchemists-Manipal/MindWave#553]
### Is your feature request related to a problem? Please describe.

This feature will help to detect the eye color of the people, further useful in determining the genetics.

### Describe the solution you'd like

Using OpenCV, I would like to implement it, using facial features.

### Additional context

As an active member of GSSOC 23, i would like you to assign me this task

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khusheekapoor** [comment]
@Tisha6661 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by Tisha6661** [comment]
@khusheekapoor  I have created a pull request regarding this task, please verify and merge it.
