### ISSUE TITLE
[Data Analytics] Flight Test Data Analytics

### ISSUE THREAD

**Issue by smty2018** [The-Data-Alchemists-Manipal/MindWave#555]
### Is your feature request related to a problem? Please describe.

A single instrumented test aircraft creates onboard data streams > 5 MB/sec, or a few gigabytes during the mission. Proper data analysis is required to handle the volume and complexity of data signals generated by modern instrumentation.

### Describe the solution you'd like

Want to create an analytics project on flight test data. Here is the dataset
[Test Flight Data - Sheet1.csv](https://github.com/The-Data-Alchemists-Manipal/MindWave/files/11909788/Test.Flight.Data.-.Sheet1.csv)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khusheekapoor** [comment]
@smty2018 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
