### ISSUE TITLE
[GSSOC'23] Employee Promotion Prediction ML Model

### ISSUE THREAD

**Issue by smty2018** [The-Data-Alchemists-Manipal/MindWave#567]
### Is your feature request related to a problem? Please describe.

The Employee Promotion Prediction ML Model employs a supervised learning, using algorithms such as decision trees, or random forests, to analyze a dataset and  predict the likelihood of an employee's promotion based on various factors such as performance, experience, skills, region of operation, etc.

### Describe the solution you'd like

dataset: 
[employee_data.csv](https://github.com/The-Data-Alchemists-Manipal/MindWave/files/11923819/employee_data.csv)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khusheekapoor** [comment]
@smty2018  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
