### ISSUE TITLE
Implementing Sentiment Analyzer using RNN

### ISSUE THREAD

**Issue by okaditya84** [The-Data-Alchemists-Manipal/MindWave#57]
## 💥 Proposal

Implementing a sentiment analyzer using RNN and NLP techniques to train the model on word2ve dataset.

**Comment by khusheekapoor** [comment]
@okaditya84 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by okaditya84** [comment]
> @okaditya84 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

Where will I be storing the weights of the dataset ?
