### ISSUE TITLE
[GSSOC '23]: Image Caption Generator using Deep Learning

### ISSUE THREAD

**Issue by sujanrupu** [The-Data-Alchemists-Manipal/MindWave#578]
An image caption generator is a system that generates textual descriptions or captions for images automatically. It combines computer vision techniques to understand the visual content of an image and natural language processing (NLP) techniques to generate descriptive captions.

- Image Caption Generator implemented using Tensorflow and Keras in a Python Jupyter Notebook. The goal is to describe the content of an image by using a CNN and RNN.

**Comment by khusheekapoor** [comment]
Hi, we have a similar issue. Hence, we cannot assign you this issue.
