### ISSUE TITLE
Handwritten digits recognition using ANN

### ISSUE THREAD

**Issue by dhruvsaxena11** [The-Data-Alchemists-Manipal/MindWave#581]
### Is your feature request related to a problem? Please describe.

I want to add this project of deep learning

### Describe the solution you'd like

I will create the ANN to recognize the handwritten digits from the dataset with good accuracy.

Please assign his issue to me.

Thank You
Dhruv Saxena

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by megha-ahirwar** [comment]
Please assign this project to me

**Comment by khusheekapoor** [comment]
Hi, we have many similar issues. Hence, we cannot assign you this one.
