### ISSUE TITLE
Add Face detection using MTCNN project

### ISSUE THREAD

**Issue by lakshmishreea122003** [The-Data-Alchemists-Manipal/MindWave#582]
### Is your feature request related to a problem? Please describe.

In this project, I have implemented face detection using MTCNN, and I have conducted a comparative analysis with OpenCV to demonstrate the superior accuracy of MTCNN in real-world face detection scenarios.

### Describe the solution you'd like

MTCNN (Multi-task Cascaded Convolutional Networks) is a popular face detection algorithm used in computer vision tasks. It is specifically designed for real-time face detection in images and videos. MTCNN consists of three stages.
No dataset required.

### Additional context

In this project, I have:
- compared the superiority of the MTCNN algorithm over opencv in face detection task.
-  keypoints detection using MTCNN.
-  extract faces in the image.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lakshmishreea122003** [comment]
I have already completed the project. You can check [here](https://github.com/lakshmishreea122003/face-detedtion-MTCNN) .
So once it is assigned to me I shall come up with a PR.

**Comment by khusheekapoor** [comment]
@lakshmishreea122003 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
