### ISSUE TITLE
Add Filter Application using Flask and OpenCV. 

### ISSUE THREAD

**Issue by lakshmishreea122003** [The-Data-Alchemists-Manipal/MindWave#583]
### Is your feature request related to a problem? Please describe.

In this project, I have used Flask and OpenCV to add filters to the frames of the video.
This project combines the power of Flask and OpenCV to create a user-friendly application where users can apply various filters to video frames. It provides an interactive and intuitive interface for experimenting with different filters and enhancing the visual appeal of images.

### Describe the solution you'd like

The UI shows up the video and several filter options which can be applied to the video frame by the user.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lakshmishreea122003** [comment]
I have completed the project as you can check [HERE](https://github.com/lakshmishreea122003/camera_flask_opencv_app) . Once assigned to me I shall come up with a PR.

**Comment by khusheekapoor** [comment]
@lakshmishreea122003 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
