### ISSUE TITLE
neural-doodle

### ISSUE THREAD

**Issue by shraddha761** [The-Data-Alchemists-Manipal/MindWave#585]
### Is your feature request related to a problem? Please describe.

generates a new image by using one, two, three or four images as inputs depending what you're trying to do: the original style and its annotation, and a target content image (optional) with its annotation (a.k.a. your doodle). 

### Describe the solution you'd like

going to made this using python

### Additional context

Assign this issue to me under GSSOC'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khusheekapoor** [comment]
@shraddha761 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
