### ISSUE TITLE
Image-processing-Matalab

### ISSUE THREAD

**Issue by shraddha761** [The-Data-Alchemists-Manipal/MindWave#586]
### Is your feature request related to a problem? Please describe.

Image sampling and quantization; spatial and frequency domain image enhancement techniques; signal processing theories used for digital image processing, such as one- and two-dimensional convolution, and two-dimensional Fourier transformation; 

### Describe the solution you'd like

morphological image processing; color models and basic color image processing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khusheekapoor** [comment]
@shraddha761  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Please create a MATLAB folder for the same.
