### ISSUE TITLE
Signature Verification using OpenCV

### ISSUE THREAD

**Issue by Tisha6661** [The-Data-Alchemists-Manipal/MindWave#596]
### Is your feature request related to a problem? Please describe.

Signature is an important authorization in any document now a says, after fingerprint. It is used in legal, property and other cases.

### Describe the solution you'd like

I would like to make a signature verification project that would verify the signature from different documents and match if it is right, signed by the same person and authorized or not.

### Additional context

Under Gssoc'23, please assign me this task.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khusheekapoor** [comment]
@Tisha6661 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by Tisha6661** [comment]
@khusheekapoor  I have created a pull request regarding this task, please verify and merge it.
