### ISSUE TITLE
Gasoline Cost Prediction ML Model

### ISSUE THREAD

**Issue by smty2018** [The-Data-Alchemists-Manipal/MindWave#599]
### Is your feature request related to a problem? Please describe.

The gasoline cost prediction ML model that uses LSTM and ARIMA algorithms to analyze historical data and other factors to forecast future gasoline prices. 

### Describe the solution you'd like

dataset:
[UK Petrol Prices.csv](https://github.com/The-Data-Alchemists-Manipal/MindWave/files/11941851/UK.Petrol.Prices.csv)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nayan2167** [comment]
I would like to work on this issue

**Comment by khusheekapoor** [comment]
@smty2018 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

@nayan2167 - we follow a first-come-first-serve policy, hence, cannot assign you this issue.
