### ISSUE TITLE
[GSSOC'23] Data Science Salaries - EDA 

### ISSUE THREAD

**Issue by sahaycodes** [The-Data-Alchemists-Manipal/MindWave#603]
### Is your feature request related to a problem? Please describe.

I'm a GSSOC'23 contributor
In this project , I would like to explore the given pattern of Data Science Salaries over the years. Would be performing 
Data Cleaning, EDA (exploratory data analysis) and would be creating a ML model out of this .

Dataset - https://www.kaggle.com/datasets/arnabchaki/data-science-salaries-2023

### Describe the solution you'd like

As said earlier, to create a ML model out of a dataset we need to understand the data as itself and all of its parameters and how they correlate with each other - EDA and Data Visualization is very much important.
Therefore, the goal is to understand the data provided and build a ML model for the same. 

### Additional context

Kindly assign this issue to me under GSSOC'23 . Waiting for response

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sahaycodes** [comment]
@khusheekapoor , kindly review this issue and assign it to me . Thank You

**Comment by nayan2167** [comment]
I would like to work on this issue

**Comment by khusheekapoor** [comment]
@sahaycodes  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
