### ISSUE TITLE
Car price prediction [Deployed project]

### ISSUE THREAD

**Issue by shruti-2412** [The-Data-Alchemists-Manipal/MindWave#604]
### Is your feature request related to a problem? Please describe.

This project aims to predict the price of cars using machine learning techniques, specifically the XGBoost algorithm. The model is trained on a dataset containing various features of cars, such as the make, model, year, mileage, fuel type, and other relevant factors. It is also deployed using Streamlit.

### Describe the solution you'd like

XGBoost is an optimized gradient-boosting algorithm that has gained popularity in machine learning competitions and has become a popular choice for predictive modeling tasks. It is known for its efficiency, accuracy, and flexibility. XGBoost combines multiple weak prediction models (decision trees) to create a strong ensemble model. 

### Additional context

Dataset link: https://www.kaggle.com/datasets/nehalbirla/vehicle-dataset-from-cardekho?select=car+data.csv

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khusheekapoor** [comment]
Hi, we have many similar issues. Hence, we cannot assign you this issue.
