### ISSUE TITLE
[GSSOC'23] Real Time Face Mask detection

### ISSUE THREAD

**Issue by alwenpy** [The-Data-Alchemists-Manipal/MindWave#606]
### Is your feature request related to a problem? Please describe.

Using Python Open CV an image processing library ,this feature detects that if a person has mask on or not.

### Describe the solution you'd like

Mask Detection on face.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khusheekapoor** [comment]
Hi, we have a similar issue. Hence, we cannot assign you this one.
