### ISSUE TITLE
[GSSOC'23 ] A CNN based classifier for Lung disease prediction for 14 Classes

### ISSUE THREAD

**Issue by xPushpeshx** [The-Data-Alchemists-Manipal/MindWave#615]
### Is your feature request related to a problem? Please describe.

The goal is to Classify 14 lung diseases,main problem here is several images contain more than 1 disease which makes it much harder to detect and falls into the category of multi-label classification rather than multi-class classification. 

### Describe the solution you'd like

The Solution to this is to develop a CNN architecture Using transfer Learning and stacking of models using different loss functions with proper data augmentation so that it correctly classifies the disease

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] Please assign me this issue

**Comment by khusheekapoor** [comment]
@xPushpeshx  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by xPushpeshx** [comment]
@khusheekapoor please review my PR #683
