### ISSUE TITLE
Virtual Painting using OpenCV

### ISSUE THREAD

**Issue by Tisha6661** [The-Data-Alchemists-Manipal/MindWave#629]
### Is your feature request related to a problem? Please describe.

OpenCV is mostly used on images and videos, I would like to explore other ways of implementing OpenCV by making a virtual painting app.

### Describe the solution you'd like

Using Opencv i would make a virtual painting app that will allow the user to paint virtually on screen.

### Describe alternatives you've considered

alternatively we can paint on images as well.

### Additional context

Under Gssoc'23 please assign me this task.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khusheekapoor** [comment]
@Tisha6661  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by Tisha6661** [comment]
@khusheekapoor  I have created a pull request regarding this task, please verify and merge it.
