### ISSUE TITLE
Thumbnailator

### ISSUE THREAD

**Issue by shraddha761** [The-Data-Alchemists-Manipal/MindWave#634]
### Is your feature request related to a problem? Please describe.

Thumbnailator's fluent interface can be used to perform fairly complicated thumbnail processing task in one simple step.

### Describe the solution you'd like

creating JPEG thumbnails of image files in a directory, all resized to a maximum dimension of 640 pixels by 480 pixels while preserving the aspect ratio of the original image can be performed 

### Additional context

Assign this issue to me under GSSOC'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by khusheekapoor** [comment]
@shraddha761 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
