### ISSUE TITLE
Medical Insurance cost prediction

### ISSUE THREAD

**Issue by tushtithakur** [The-Data-Alchemists-Manipal/MindWave#65]
## 💥 Proposal

This model is designed to build a system that can predict the medical insurance cost with the help of Machine Learning. 
I will be using this dataset-https://www.kaggle.com/datasets/mirichoi0218/insurance
I would like to contribute to this project as a part of @GSSOC'23.
Please assign the task to me. Thank you.

**Comment by khusheekapoor** [comment]
@tushtithakur - a similar issue already exists (#18). Hence, we cannot assign you this issue.
