### ISSUE TITLE
Adding a object detection feature using YOLO v8

### ISSUE THREAD

**Issue by A15h** [The-Data-Alchemists-Manipal/MindWave#650]
### Is your feature request related to a problem? Please describe.

We can add a object detection feature using YOLO which is pre-trained and also fine tune it using a custom dataset we have created. 

### Describe the solution you'd like

This feature will be able to detect objects by surrounding them with boundary boxes and labelling them as a person or wto whichever category it belongs to.

### Describe alternatives you've considered

We can also use RCNN based approach where we can use Tensorflow Object Detection and fine tune it with a custom dataset.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by A15h** [comment]
@khusheekapoor please assign this issue to me. I would like to contribute as a GSSOC contributor.

**Comment by khusheekapoor** [comment]
Hi, we have many similar issues. Hence, we cannot assign you this one.
