### ISSUE TITLE
Add Handwritten Digit Recognition using Convolutional Neural Networks (CNNs)

### ISSUE THREAD

**Issue by lakshmishreea122003** [The-Data-Alchemists-Manipal/MindWave#667]
### Is your feature request related to a problem? Please describe.

dataset = MNIST
LeNet architecture used
Calculation metrics = F1 score

### Describe the solution you'd like

This is a TensorFlow project for image classification using the MNIST dataset.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lakshmishreea122003** [comment]
Do assign it to me

**Comment by khusheekapoor** [comment]
Hi, we have many similar issues. Hence, we cannot assign you this one.
