### ISSUE TITLE
[MODEL] Flight Price Prediction Model with GUI

### ISSUE THREAD

**Issue by himanshu-03** [The-Data-Alchemists-Manipal/MindWave#68]
## 💥 Proposal

Hello!
I am Himanshu Agarwal, a proud contribtuor at GSSoC '23. I would like to the contribute to this repo.

Things I will be doing as of now:

- [x] Build a Flight Price Prediction Model
- [x] Getting live user data on the website and give predictions accordingly.

**Comment by khusheekapoor** [comment]
@himanshu-03  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by himanshu-03** [comment]
Sure, will be working in the given deadline

**Comment by himanshu-03** [comment]
Hello @khusheekapoor !

I have successfully implemented the Flight Price Prediction Model.
However, I was able to deploy it on local host on Streamlit but I am not able to deploy the project on Streamlit Cloud

**Comment by himanshu-03** [comment]
I am okay if it comes under the Machine Learning Category, so if possible can you please update the label so that I create a PR for the Machine Learning Category

**Comment by himanshu-03** [comment]
> ## 💥 Proposal
> Hello! I am Himanshu Agarwal, a proud contribtuor at GSSoC '23. I would like to the contribute to this repo.
> 
> Things I will be doing as of now:
> 
> * [x]  Build a Flight Price Prediction Model
> * [x]  Getting live user data on the website and give predictions accordingly.

💯 Both Tasks Done

**Comment by himanshu-03** [comment]
I have a question for the DEPLOYED PROJECTS section

Do we have to link the 'README.md' file with the folder link?
Or with the Streamlit hosted link?

Otherwise there is no way a person can see the deployed project hosted on Streamlit, they would be just seeing the directory structure.

**Comment by khusheekapoor** [comment]
Hi, you have to link both: the link and the directory.

**Comment by himanshu-03** [comment]
I have included both the links in the README.md file, do review the PR ✌️
