### ISSUE TITLE
Diabetes Prediction using all ML algorithms

### ISSUE THREAD

**Issue by ManaswiKasiraju** [The-Data-Alchemists-Manipal/MindWave#69]
I am a GSSOC'23 contributor.
In this project based on the features like blood Pressure and others, a person will be predicted whether he is diabetic or not using different ML models. Thereby, the most accurate model can be chosen. 

Please assign me under the label GSSOC'23.

**Comment by ManaswiKasiraju** [comment]
I am a GSSOC'23 contributor.
I would like to work on the mentioned project under GSSOC'23 label.
Please assign me.

**Comment by khusheekapoor** [comment]
@ManaswiKasiraju - a similar issue already exists (#27). Hence, we cannot assign you this issue.

**Comment by Krishna9027** [comment]
I am a GSSoC'23 contributor . I would like to work on this issue by training and testing a model using ML algorithms so that it can predict diabetes . Please  assign me this issue .
