### ISSUE TITLE
Linear Regression on the California Housing Dataset

### ISSUE THREAD

**Issue by khusheekapoor** [The-Data-Alchemists-Manipal/MindWave#7]
## 💥 Proposal

To implement the Linear Regression algorithm on the California Housing Dataset.
Link to the Dataset: https://www.kaggle.com/datasets/camnugent/california-housing-prices

**Comment by MirrorCraze** [comment]
Hi! Can I take this one?

I read the contribution guidelines and I want to ask two questions
1. What kinds of library do you have in mind for this task? (e.g. scikit-learn, statmodels, etc.)
2. Do you want files to be in .py or .ipynb?

**Comment by Soumya-Kushwaha** [comment]
Hey @khusheekapoor I'd like to work on this!

**Comment by khusheekapoor** [comment]
Hello @MirrorCraze! Thank you for showing interest in this issue. You can use any python library for this task, making sure that you document why you've used a certain library and explaining all the features of the same. We would prefer if the files are in .ipynb format, as they contain the code, the output, and the documentation all in one place, however, if you plan to deploy the project, you can create a .py file with FastAPI for the backend and Streamlit for the frontend.

However, please do not start working on this as yet, as this repository is made specifically for GirlScript Summer of Code 2023, and only participants of the same will be assigned issues to work on. If you're a participant, then please wait until the 20th of May for the issue to be assigned to you. If not, then I am really sorry, but I will not be able to assign this issue to you. However, do stay tuned to The Data Alchemist's GitHub, as we will be hosting many other Open Source projects soon!

All the best!

**Comment by khusheekapoor** [comment]
Hello @Soumya-Kushwaha!
This repository is made specifically for GirlScript Summer of Code 2023, and only participants of the same will be assigned issues to work on. If you're a participant, then please wait until the 20th of May for the issue to be assigned to you. If not, then I am really sorry, but I will not be able to assign this issue to you. However, do stay tuned to The Data Alchemist's GitHub, as we will be hosting many other Open Source projects soon!

All the best!

**Comment by MirrorCraze** [comment]
> Hello @MirrorCraze! Thank you for showing interest in this issue. You can use any python library for this task, making sure that you document why you've used a certain library and explaining all the features of the same. We would prefer if the files are in .ipynb format, as they contain the code, the output, and the documentation all in one place, however, if you plan to deploy the project, you can create a .py file with FastAPI for the backend and Streamlit for the frontend.
> 
> However, please do not start working on this as yet, as this repository is made specifically for GirlScript Summer of Code 2023, and only participants of the same will be assigned issues to work on. If you're a participant, then please wait until the 20th of May for the issue to be assigned to you. If not, then I am really sorry, but I will not be able to assign this issue to you. However, do stay tuned to The Data Alchemist's GitHub, as we will be hosting many other Open Source projects soon!
> 
> All the best!

Whelp, I'm not a participant :( 

Good luck to the Summer of Code project!

**Comment by dibyarupnath** [comment]
I would like to work on this issue. I have some experience with housing price prediction and would like to try to work on this project and see if my pull request gets accepted.

**Comment by hkcs1206** [comment]
I want to work on this issue; I already applied different regression analyses for AQI prediction, which was my recent project, so Kindly assign it to me. I am GSSOC Contributor.

**Comment by khusheekapoor** [comment]
@Soumya-Kushwaha - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!

@dibyarupnath, @hkcs1206  - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue and use the same algorithm (linear regression) on a different dataset.

**Comment by itsdebartha** [comment]
@khusheekapoor I would like to implement this algorithm using the R programming language, instead of Python. Can you assign me for the same?

**Comment by s0oraj** [comment]
Hi @khusheekapoor  , iam a GSSOC23 contributer and I would like to resolve this issue

Can you assign me this issue? Or any other issues you might have?
Heres My Resume which you might find useful: [Resume](https://github.com/s0oraj/Animus/files/11521330/Resume.pdf)
Here is my background in ML:

1) 6 months plus experience in working under college professors for research project on medical image classification.
2) Got 228 global rank in Amazon ML Challenge 2023 out of 30000+ teams participating.
3) Experienced with trainig machine Learning Models. Including image preprocessing techniues such as histrogram equilization, augmentation, stationary wavelet transformation, image segmentation. Along with feature extraction from models like resnet50 inceptionv3 vgg16 etc

Looking forward to hear from you.

**Comment by khusheekapoor** [comment]
@itsdebartha @s0oraj @yash-jain-1   - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue and use the same algorithm (linear regression) on a different dataset.

**Comment by Soumya-Kushwaha** [comment]
Thank you @khusheekapoor . I'll start working on it right away!

**Comment by itsdebartha** [comment]
@khusheekapoor Will I be uploading an R Markdown(`.Rmd`) file? Or just an R Script (`.R`)?

**Comment by A15h** [comment]
hi @khusheekapoor  
I would really like to work on this issue . Please assign this issue to me. I am a contributor of GSSOC'23.

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by khusheekapoor** [comment]
@itsdebartha - an r markdown file would have better documentation, making it easier for first time users to read your code. Hence, a markdown file would be preferred.

@A15h @UditSharma9999 - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue on the similar lines.

**Comment by sarahcodebyte** [comment]
Hi @khusheekapoor, I am a GSSOC'23 contributor and would like to be assigned this issue. 
Thank you.
