### ISSUE TITLE
Mobile Price Prediction by the best possible classifier

### ISSUE THREAD

**Issue by lcs2022026** [The-Data-Alchemists-Manipal/MindWave#73]
💥 Proposal:-
@khusheekapoor 
to predict the mobile price by using different classification methods and selecting the  best out of them .
the dataset i am gonna use is:-https://www.kaggle.com/datasets/iabhishekofficial/mobile-price-classification
I am GSSOC'23 contributor and would like to do this project 
so please assign me it

**Comment by lcs2022026** [comment]
💥 Proposal:-
@khusheekapoor
to predict the mobile price by using different classification methods and selecting the best out of them .
the dataset i am gonna use is:-https://www.kaggle.com/datasets/iabhishekofficial/mobile-price-classification
I am GSSOC'23 contributor and would like to do this project
so please assign me it
@khusheekapoor

**Comment by khusheekapoor** [comment]
@lcs2022026 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
