### ISSUE TITLE
Bank Churn Classification

### ISSUE THREAD

**Issue by lcs2022026** [The-Data-Alchemists-Manipal/MindWave#74]
💥 Proposal
I would like to classify the customers of bank into different categories ,so that they can make different programs for different customers
i would do this doing different models[SVM,RandomForest,Logistic] and then would hypertune it to select best model and best parameters
the dataset i would use is:-https://www.kaggle.com/datasets/radheshyamkollipara/bank-customer-churn

**Comment by lcs2022026** [comment]
I would like to classify the customers of bank into different categories ,so that they can make different programs for different customers
i would do this doing different models[SVM,RandomForest,Logistic] and then would hypertune it to select best model and best parameters
I am a GSSOC'23 contributor 
i would like to do this project so please assign me this
the dataset i would use is:-https://www.kaggle.com/datasets/radheshyamkollipara/bank-customer-churn

**Comment by khusheekapoor** [comment]
@lcs2022026 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
