### ISSUE TITLE
Car Acceptability Classification  by the best model possible

### ISSUE THREAD

**Issue by lcs2022026** [The-Data-Alchemists-Manipal/MindWave#75]
💥 Proposal
@khusheekapoor 
to make a model that could tell a cars design would be accepted or not based on its sizes of different components
i will use many different models and then i would select the model which would give me the best results 
i would do this by using GridSearchCV
I am  GSSOC'23 contributor and would like to do this project 
so please assign it to me

**Comment by lcs2022026** [comment]
💥 Proposal
@khusheekapoor 
to make a model that could tell a cars design would be accepted or not based on its sizes of different components
i will use many different models and then i would select the model which would give me the best results 
i would do this by using GridSearchCV
I am  GSSOC'23 contributor and would like to do this project 
so please assign it to me
@khusheekapoor

**Comment by khusheekapoor** [comment]
@lcs2022026 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
