### ISSUE TITLE
Image Based Species Recognition (Cats and Dogs) using Deep Learning

### ISSUE THREAD

**Issue by ranodeepbanerjee** [The-Data-Alchemists-Manipal/MindWave#76]
Hey, I'm a GSSoC'23 contributor and I would like to work on this project. I will be using the using the Cats and dogs dataset available at Kaggle https://www.kaggle.com/datasets/tongpython/cat-and-dog/versions/1 
 Kindly assign this to me and I'm ready to start working !  Thank you

**Comment by ranodeepbanerjee** [comment]
Kindly assign this to me, thank you!

**Comment by khusheekapoor** [comment]
@ranodeepbanerjee - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
