### ISSUE TITLE
Twitter Sentiment Analysis - NLP

### ISSUE THREAD

**Issue by ranodeepbanerjee** [The-Data-Alchemists-Manipal/MindWave#77]
# Proposal

Sentiment Analysis using the tweets of people during the covid period using best classifier possible.

**Comment by ranodeepbanerjee** [comment]
I'm a GSSoC'23 contributor and I would like to work on this project! Kindly assign this to me. Thank you.

**Comment by khusheekapoor** [comment]
@ranodeepbanerjee  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by ranodeepbanerjee** [comment]
@khusheekapoor Hello, I have opened a pull request. Kindly merge it if everything is alright and give the GSSOC tag. 
Thank you.
