### ISSUE TITLE
Face Mask Detection 

### ISSUE THREAD

**Issue by ranodeepbanerjee** [The-Data-Alchemists-Manipal/MindWave#78]
# Proposal

A face mask detection model using computer vision.

**Comment by ranodeepbanerjee** [comment]
I'm a GSSoC'23 contributor and I would like to work on it. Please assign this to me.

**Comment by khusheekapoor** [comment]
@ranodeepbanerjee - a similar issue has already been assigned (#31). Hence, we cannot assign you this issue.

**Comment by Krishna9027** [comment]
I am a GSSoc'23 contributor .I would like to work on this project . Kindly assign this issue to me .
