### ISSUE TITLE
Improving visualization of the Bollywood movie dataset 

### ISSUE THREAD

**Issue by adhikari-pratik** [The-Data-Alchemists-Manipal/MindWave#79]
I would like to enhance the graphs and plots in the explanatory analysis.

1. Adding title to the plots 
2. Using proper x and y labels 
3. Improvising heat map for showing correlation

I would like you to assign me with this issue under GSSOC'23. Thank you!

**Comment by khusheekapoor** [comment]
@adhikari-pratik  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by snehasingh3013** [comment]
hi @khusheekapoor 
I would really like to work on this. Please assign this to me. I have worked on projects in the same field. I am a contributor of GSSOC'23.

**Comment by khusheekapoor** [comment]
@snehasingh3013 - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue on the similar lines.
