### ISSUE TITLE
Logistic Regression on the Titanic Dataset

### ISSUE THREAD

**Issue by khusheekapoor** [The-Data-Alchemists-Manipal/MindWave#8]
## 💥 Proposal

To implement the Logistic Regression algorithm on the Titanic Dataset.
Link to the Dataset: https://www.kaggle.com/datasets/pavlofesenko/titanic-extended

**Comment by Soumya-Kushwaha** [comment]
I'd like to work on this @khusheekapoor

**Comment by khusheekapoor** [comment]
Hello @Soumya-Kushwaha!
This repository is made specifically for GirlScript Summer of Code 2023, and only participants of the same will be assigned issues to work on. If you're a participant, then please wait until the 20th of May for the issue to be assigned to you. If not, then I am really sorry, but I will not be able to assign this issue to you. However, do stay tuned to The Data Alchemist's GitHub, as we will be hosting many other Open Source projects soon!

All the best!

**Comment by Soumya-Kushwaha** [comment]
I am a participant in GirlScript Summer of Code. See you soon!

**Comment by dibyarupnath** [comment]
I would like to work on this issue. I have some experience with logistic regression also and would like to try to work on this project and see if my pull request gets accepted. thank you for the opportunity.

**Comment by NisargPipaliya** [comment]
i would like to work on this issue.
contributor at girl script summer of code

**Comment by PiyushaGhodake** [comment]
@khusheekapoor I would like to work on this project.I  am contributor at GirlScript Summer of Code. I have experience working on logistic regression.

**Comment by TripleteSumit** [comment]
@khusheekapoor, I would also like to contribute to this project. As a GSSOC contributor, I believe this project aligns perfectly with my technical expertise. I have a good understanding and experience working with this algorithm.

**Comment by khusheekapoor** [comment]
@Soumya-Kushwaha - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!
 
@dibyarupnath @TripleteSumit @NisargPipaliya @PiyushaGhodake - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue and use the same algorithm (logistic regression) on a different dataset.

**Comment by s0oraj** [comment]
Hi @khusheekapoor  , iam a GSSOC23 contributer and I would like to resolve this issue

Can you assign me this issue? Or any other issues you might have?
Heres My Resume which you might find useful: [Resume](https://github.com/s0oraj/Animus/files/11521330/Resume.pdf)
Here is my background in ML:

1) 6 months plus experience in working under college professors for research project on medical image classification.
2) Got 228 global rank in Amazon ML Challenge 2023 out of 30000+ teams participating.
3) Experienced with trainig machine Learning Models. Including image preprocessing techniues such as histrogram equilization, augmentation, stationary wavelet transformation, image segmentation. Along with feature extraction from models like resnet50 inceptionv3 vgg16 etc

Looking forward to hear from you.

**Comment by khusheekapoor** [comment]
@s0oraj   - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue and use the same algorithm (logistic regression) on a different dataset.

**Comment by Soumya-Kushwaha** [comment]
Thank you @khusheekapoor

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.
