### ISSUE TITLE
Implement Image Captioning

### ISSUE THREAD

**Issue by SAPNILPATEL** [The-Data-Alchemists-Manipal/MindWave#80]
## 💥 Proposal

The goal of this project is to generate accurate and semantically meaningful captions for different types of images. 

I would like to request you that please assign it to me under the tag/label GSSoC'23.

**Comment by khusheekapoor** [comment]
@SAPNILPATEL - a similar issue has already been assigned (#40). Hence, we cannot assign you this issue.

**Comment by SAPNILPATEL** [comment]
ok no problem.

**Comment by SAPNILPATEL** [comment]
Can I collaborate with that person and work on the same issue?

**Comment by Krishna9027** [comment]
### **PROPOSAL**

I would like to work on this issue to generate a model that can classify the images under certain meaningful actions . 

Please assign me this issue under GSSoC'23 contributor.
