### ISSUE TITLE
Retina damage detection from OCT images

### ISSUE THREAD

**Issue by nk-droid** [The-Data-Alchemists-Manipal/MindWave#81]
An image classification model to predict whether an input image contains a damage retina or not. In case of damage retina, the model will give choroidal neovascularization (CNV), Diabetic macular edema (DME) or DRUSEN as output.

Dataset link - https://www.kaggle.com/code/paultimothymooney/detect-retina-damage-from-oct-images

Please assign me this task. Thank you.

**Comment by khusheekapoor** [comment]
@nk-droid - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
