### ISSUE TITLE
Object Prediction Model

### ISSUE THREAD

**Issue by tushtithakur** [The-Data-Alchemists-Manipal/MindWave#82]
## 💥 Proposal
Here, I would like to create a prediction model to check whether the object is a rock or mine.
I would like to contribute to this project as a part of @GSSOC'23.
Please assign the task to me. Thank you.

**Comment by khusheekapoor** [comment]
@tushtithakur  - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
