### ISSUE TITLE
Easiest Diabetes Classification 

### ISSUE THREAD

**Issue by snehasingh3013** [The-Data-Alchemists-Manipal/MindWave#87]
The dataset consists of 100+ patient records. Each record contains the following information:
Age: The patient's age, in years.
Gender: The patient's gender, male or female.
BMI: The patient's body mass index (BMI), a measure of weight relative to height.
Blood pressure: The patient's blood pressure, in mmHg.
FBS: The patient's fasting blood sugar, in mg/dL.
HbA1c: The patient's hemoglobin A1c, a measure of blood sugar control over the past 3 months.
Family history of diabetes: Whether the patient has a family history of diabetes.
Smoking: Whether the patient smokes.
Diet: Whether the patient has a poor or healthy diet.
Exercise: Whether the patient exercises regularly.
Diagnosis: The patient's diagnosis, either diabetes or no diabetes.

**Comment by snehasingh3013** [comment]
hi @NisargPipaliya
I would really like to work on this issue. Please assign this issue to me. I have worked on projects in the same field. I am a contributor of GSSOC'23.

**Comment by khusheekapoor** [comment]
@snehasingh3013 - we already have diabetes classification issue (#69). Hence, we will not be able to assign you the same.
