### ISSUE TITLE
LeNet on the MNIST Dataset

### ISSUE THREAD

**Issue by khusheekapoor** [The-Data-Alchemists-Manipal/MindWave#9]
## 💥 Proposal

To implement the LeNet Architecture on the MNIST Dataset.
Link to the Dataset: https://www.kaggle.com/datasets/hojjatk/mnist-dataset

**Comment by dibyarupnath** [comment]
I would like to work on this issue. I have already done a small project on MNIST, it's on my github profile. I am not familiar with LeNet but I am willing to learn.

**Comment by hkcs1206** [comment]
Hey, 
Recently I worked on an Image dataset where I implemented various architectures like UNET, PSPNET, etc, for segmentation, I have experience in deep learning, so could you assign it to me?

**Comment by khusheekapoor** [comment]
@dibyarupnath - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! There are several articles on Medium/ notebooks on Kaggle that you can refer to while coding this project. As for the linear/ logistic regression issues, you can refer to those threads for their status.

@hkcs1206 - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue and use the same algorithm (LeNet) on a different dataset.

**Comment by KEERTHI1912** [comment]
Hello, I would like to work on this issue as I am familiar with various other models of deep learning such as Alexnet, RESNET, LSTM, etc. Thus, would love to learn LeNet and contribute to this project.

**Comment by s0oraj** [comment]
Hi @khusheekapoor  , iam a GSSOC23 contributer and I would like to resolve this issue

Can you assign me this issue? Or any other issues you might have?
Heres My Resume which you might find useful: [Resume](https://github.com/s0oraj/Animus/files/11521330/Resume.pdf)
Here is my background in ML:

1) 6 months plus experience in working under college professors for research project on medical image classification.
2) Got 228 global rank in Amazon ML Challenge 2023 out of 30000+ teams participating.
3) Experienced with trainig machine Learning Models. Including image preprocessing techniues such as histrogram equilization, augmentation, stationary wavelet transformation, image segmentation. Along with feature extraction from models like resnet50 inceptionv3 vgg16 etc

Looking forward to hear from you.

**Comment by khusheekapoor** [comment]
@s0oraj @KEERTHI1912  - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue and use the same algorithm (linear regression) on a different dataset.
