### ISSUE TITLE
Chronic Kidney Diseases Prediction

### ISSUE THREAD

**Issue by ayush-09** [The-Data-Alchemists-Manipal/MindWave#91]
## 💥 Proposal

The aim of this project is to develop a predictive model for **chronic kidney disease (CKD)** based on patient data and relevant medical factors. The objective is to accurately predict the presence or absence of CKD in patients, aiding in early detection and timely intervention.

Please assign me this task.

**Comment by khusheekapoor** [comment]
@ayush-09 - which algorithms will you be using?

**Comment by ayush-09** [comment]
@khusheekapoor My intiution is to do first Data Preprocess and perform EDA on the kidney dataset and then do the feature encoding on the dataset which helps me to get the best features for the model. On the basis of classification or regression problem I made the best ML model for the prediction of CKD with best results and accuracy.

Summary

Project involves data preprocessing, exploratory data analysis (EDA), and feature engineering. It aims to develop an accurate predictive model by selecting the best machine learning algorithm based on the nature of the problem (classification or regression). The model's performance is optimized through hyperparameter tuning.

**Comment by khusheekapoor** [comment]
@ayush-09 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Comment by ayush-09** [comment]
Hello @khusheekapoor,
I have opened a pull request. Kindly merge it if everything is alright and give the GSSOC tag.
Thank you.
