### ISSUE TITLE
Thyroid disease Classification

### ISSUE THREAD

**Issue by lcs2022026** [The-Data-Alchemists-Manipal/MindWave#95]
💥 Proposal
I want to create a model that could classify the type of thyroid disease 
i will do this by using searchGridCV and i would select the best classifier possible
@khusheekapoor  
i am GSSOC'23 contributor 
i want to do this project so please kindly assign me this
the dataset i would use is:- https://www.kaggle.com/datasets/emmanuelfwerr/thyroid-disease-data

**Comment by lcs2022026** [comment]
💥 Proposal
I want to create a model that could classify the type of thyroid disease 
i will do this by using searchGridCV and i would select the best classifier possible
@khusheekapoor  
i am GSSOC'23 contributor 
i want to do this project so please kindly assign me this
the dataset i would use is:- https://www.kaggle.com/datasets/emmanuelfwerr/thyroid-disease-data

**Comment by khusheekapoor** [comment]
@lcs2022026 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
