### ISSUE TITLE
[GSSOC'23] Separate folder for NLP Projects and adding News Summariser

### ISSUE THREAD

**Issue by mkswagger** [The-Data-Alchemists-Manipal/MindWave#96]
## 💥 Proposal :  Creating a separate folder for  NLP Projects and Include News Summariser

Description: This proposal suggests adding a dedicated folder within the repository to house NLP projects. Specifically, it recommends including a project for Summarisation of news. This project will demonstrate NLP techniques and provide valuable insights. The folder structure and documentation should be updated accordingly to accommodate this addition.

Additional Information:  expanding the repository's scope and offer meaningful NLP examples, starting with the News Summariser

**Comment by mkswagger** [comment]
Hi ,
I am a contrbutor in GSSOC'23, Can you please assign this issue to me

**Comment by reshma045** [comment]
Hello, I'm GSSoC'23 Contributor. Please assign me this issue. I want to work on this and contribute to this.

**Comment by khusheekapoor** [comment]
@mkswagger - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Please add this in the Deployed Projects folder. Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
