### ISSUE TITLE
Tomato Leaf Disease Detection by using CNN

### ISSUE THREAD

**Issue by lcs2022026** [The-Data-Alchemists-Manipal/MindWave#98]
Proposal:-
I want to create a convolutional neural network(CNN) model that can detect the tomato leaf disease
the dataset i want to use is:- https://www.kaggle.com/datasets/kaustubhb999/tomatoleaf/code

**Comment by lcs2022026** [comment]
Proposal:-
I want to create a convolutional neural network(CNN) model that can detect the tomato leaf disease
the dataset i want to use is:- https://www.kaggle.com/datasets/kaustubhb999/tomatoleaf/code
@khusheekapoor  
i want to do this project 
I am a GSSOC'23 contributor 
so kindly assign me this issue

**Comment by khusheekapoor** [comment]
@lcs2022026 - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
