### ISSUE TITLE
[GSSOC'23] Bank Fraud Detection Model using false positives from the data

### ISSUE THREAD

**Issue by mkswagger** [The-Data-Alchemists-Manipal/MindWave#99]
# Title: Proposal: Add Bank Fraud Detection Model

#Description: 
Suggesting the addition of a bank fraud detection model to the repository. This model will help identify fraudulent transactions, mitigating financial losses.  to enhance the repository and combat bank fraud.

Dataset : https://www.kaggle.com/datasets/ealaxi/banksim1

**Comment by mkswagger** [comment]
Hi ,
I am a contributor in GSSOC'23, Can you please assign this issue to me

**Comment by khusheekapoor** [comment]
@mkswagger - which models will you be using for the same?

**Comment by mkswagger** [comment]
I have 2 methods to implement this, one I am exploring is usual classification algorithms and the other one is using XGBclassifier and involving graphs to plot the false positive rate

**Comment by khusheekapoor** [comment]
@mkswagger - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.
